cs2_phrases = [
    "🔫 Ese headshot fue tan rápido que ni el server lo creyó.",
    "🧨 La bomba plantada, pero ¿dónde está el que la defiende?",
    "👀 Camper nivel ninja activado.",
    "💥 Boom, otro enemigo que no vio venir la granada.",
    "👀 Miras el minimapa, pero aún así te matan.",
    "🔫 ¿Ese disparo? Profesional… del lado equivocado.",
    "💣 La bomba explotó y tú seguías en spawn.",
    "👎 Intentando revivir a tu equipo… solo lograste morir otra vez.",
    "🕵️‍♂️ Ese camper merece un premio… o un ban.",
    "💥 Headshot de ensueño, lástima que fue en bot.",
    "🔫 Disparaste primero y fallaste igual que siempre.",
    "🧨 Plantar la bomba es fácil, desactivarla no tanto.",
    "👀 Tus pasos son tan ruidosos que hasta el enemigo te saluda.",
    "💣 Intentaste lanzar la granada y te explotó en la cara.",
    "🔫 Ese spray controlado fue… interesante, pero mortal para ti.",
    "👎 Más muerto que las esperanzas de tu equipo.",
    "💥 Gran jugada… si fuera otra partida.",
    "🕵️‍♂️ Ese sniper sigue ahí… ¿alguien le avisa que la partida terminó?",
    "🔫 Tu puntería es legendaria… para fallar.",
    "🧨 La bomba explotó, y tú estabas mirando el chat.",
    "👀 Miras la esquina, pero el enemigo estaba detrás de ti.",
    "💣 Intentaste molestar al equipo enemigo… y lograste suicidarte.",
    "🔫 Ese disparo fue tan preciso que ni tú lo entendiste.",
    "👎 Moriste mientras contabas tu score.",
    "💥 Otro enemigo eliminado… gracias a que corriste delante de él.",
    "🕵️‍♂️ Camper detectado: se encuentra en su hábitat natural.",
    "🔫 Headshot fantasma, solo en tu imaginación.",
    "🧨 La granada voló, el enemigo también… tú no tanto.",
    "👀 Te escondiste detrás de la caja… y fue lo peor que hiciste.",
    "💣 Explosión épica, y tú justo en el centro.",
    "🔫 Ese disparo a ciegas fue… sorprendentemente inútil.",
    "👎 Equipo eliminado, tú el último en caer.",
    "💥 Esa jugada era digna de highlight… para el enemigo.",
    "🕵️‍♂️ Alguien dijo camper… era solo tu reflejo.",
    "🔫 Tu spray controlado destruyó… tu confianza.",
    "🧨 Plantaste la bomba, olvidaste desactivarla.",
    "👀 Esa mira cruzada fue solo decorativa.",
    "💣 Granada lanzada… directo a tu pie.",
    "🔫 Headshot doble… pero tus bots lo lograron, no tú.",
    "👎 Caíste en la trampa… de nuevo.",
    "💥 Ese salto no salvó tu vida.",
    "🕵️‍♂️ Observando desde la ventana… enemigo te ve primero.",
    "🔫 Disparo épico, enemigo desaparecido… tú también.",
    "🧨 Intentaste flash, pero cegaste a tu equipo.",
    "👀 Sigilo nivel ninja… detectado a 3 km.",
    "💣 Ese gran salto fue tan mortal como tu ego.",
    "🔫 Spray controlado, objetivo eliminado… por accidente.",
    "👎 Otro death… ¿empezamos a contar ya?",
    "💥 Explosión de bomba, tú mirando desde lejos.",
    "🕵️‍♂️ Camper activo, saludamos con respeto.",
    "🔫 Ese headshot fue legendario… si fuera en otro mapa.",
    "🧨 Granadas voladoras… y tú volando también.",
    "👀 Esa esquina no te salvó de morir.",
    "💣 Explosionando, tú viendo cómo pasa todo.",
    "🔫 Puntería épica… en sentido contrario.",
    "👎 Otra muerte inesperada, sorpresa total.",
    "💥 Ese rush fue heroico… para el enemigo.",
    "🕵️‍♂️ Scout detectado, se mueve lento… igual que tú.",
    "🔫 Disparo al azar, impacto inesperado… enemigo sobrevive.",
    "🧨 Intentaste molestar al enemigo, pero fuiste tú el molestado.",
    "👀 Miraste el minimapa… tarde.",
    "💣 Esa granada era tu fin, lo sabías.",
    "🔫 Headshot imaginario, realidades alternativas.",
    "👎 Te caíste al vacío mientras planeabas tu estrategia.",
    "💥 Esa estrategia fue explosiva… para tu equipo.",
    "🕵️‍♂️ Camper en la esquina… esperando la eternidad.",
    "🔫 Ese disparo fue tan rápido que ni tú lo viste.",
    "🧨 Bombardeo aéreo… y tú en el epicentro.",
    "👀 Mirada sigilosa… pero todos te vieron.",
    "💣 Intentaste curar… explosión lo impidió.",
    "🔫 Spray a lo loco… éxito relativo.",
    "👎 Caíste solo, héroe de la soledad.",
    "💥 Jugada épica… para el enemigo.",
    "🕵️‍♂️ Camper detectado… saludamos con respeto.",
    "🔫 Headshot glorioso… en tu imaginación.",
    "🧨 La bomba explotó y tú estabas distraído.",
    "👀 Miras la esquina, el enemigo ya está en spawn.",
    "💣 Intentaste volar la puerta… y tú volaste primero.",
    "🔫 Tu puntería hizo historia… en sentido inverso.",
    "👎 Otro death, tus estadísticas lo confirman.",
    "💥 Esa jugada fue heroica… para el enemigo.",
    "🕵️‍♂️ Scout detectado, pero tú eras peor.",
    "🔫 Disparo certero… si fuera hacia otro lado.",
    "🧨 Intentaste molestar al enemigo, pero fue tu fin.",
    "👀 Esa mira fue decorativa.",
    "💣 Granada lanzada… directo a tu cara.",
    "🔫 Headshot doble… en tu cabeza.",
    "👎 Caíste otra vez, épico.",
    "💥 Salto heroico… solo para morir.",
    "🕵️‍♂️ Observando desde lejos… y muerto.",
    "🔫 Disparo letal… para ti mismo.",
    "🧨 Flash lanzado… cegaste a tu equipo.",
    "👀 Sigilo fallido, detectado.",
    "💣 Explosión épica, tú en el centro.",
    "🔫 Spray mortal… para tu moraleja.",
    "👎 Otra muerte, otra historia.",
    "💥 Rush épico… enemigo sonríe.",
    "🕵️‍♂️ Scout activo… eres la presa.",
    "🔫 Headshot imposible… logrado por el enemigo.",
    "🧨 Intentaste molestar… fuiste molestado.",
    "👀 Mirada tardía, enemigo activo.",
    "💣 Esa granada era tu fin.",
    "🔫 Headshot imaginario… realidad triste.",
    "👎 Caíste solo, otra vez.",
    "💥 Estrategia explosiva… para el enemigo."
]
