dayz_phrases = [
    "🩸 Más tiempo buscando comida que sobreviviendo.",
    "🔪 La confianza mata más que los zombis.",
    "🥫 ¿Comida enlatada o muerte? Elegir nunca fue tan fácil.",
    "💀 Sobrevivir 5 minutos sin morir ya es un logro.",
    "🏹 Tu arco es más peligroso para ti que para los zombis.",
    "🥾 Caminando hacia la muerte… con estilo.",
    "🍗 La comida desaparece antes que tus enemigos.",
    "🩸 Te crees listo, hasta que un zombi te abraza.",
    "🔪 Ese cuchillo sirve más para rascarte que para matar.",
    "🥫 Abriste la lata… y apareció otro jugador.",
    "💀 Tu plan de supervivencia es solo un meme.",
    "🏹 Apuntaste… y fallaste como siempre.",
    "🥾 Sobrevivir con hambre es un arte que no dominas.",
    "🍗 Esa pieza de carne durará menos que tu vida.",
    "🩸 Los zombis tienen mejor puntería que tú.",
    "🔪 Sigues vivo… por pura suerte.",
    "🥫 La comida se pudre y tú también.",
    "💀 Caíste en la trampa… literal y figuradamente.",
    "🏹 Tu flecha volvió a ti, como un boomerang mortal.",
    "🥾 Corriendo del zombi… directo al precipicio.",
    "🍗 Ese pollo sabe más que tú sobre supervivencia.",
    "🩸 Intentaste saquear… te saquearon primero.",
    "🔪 Ese cuchillo corta… tu ego, principalmente.",
    "🥫 Abriste una lata y apareció el enemigo.",
    "💀 Sobrevivir a un jugador es más difícil que a los zombis.",
    "🏹 Flechazo épico… en tu propio pie.",
    "🥾 Corres hacia tu muerte, pero con estilo.",
    "🍗 Comer antes de morir es un lujo que no tendrás.",
    "🩸 Ese zombi te persigue… y te alcanza.",
    "🔪 Acabas de descubrir que no sabes pelear.",
    "🥫 Abriste la lata… y salió una explosión de enemigos.",
    "💀 Moriste, pero al menos fue con dignidad… más o menos.",
    "🏹 Apuntaste, disparaste… y fallaste espectacularmente.",
    "🥾 Caminando hacia la muerte con confianza absurda.",
    "🍗 Ese snack fue más rápido que tú corriendo.",
    "🩸 Tu sangre es el nuevo manjar de los zombis.",
    "🔪 El cuchillo era de adorno, no de defensa.",
    "🥫 La comida se acabó antes que tu paciencia.",
    "💀 Te atraparon mientras mirabas el mapa.",
    "🏹 Flecha perdida… destino: tu pierna.",
    "🥾 Sigues corriendo… hacia más zombies.",
    "🍗 Esa comida sabe a derrota.",
    "🩸 Cada zombi que pasa te recuerda tu torpeza.",
    "🔪 Ese cuchillo es más decorativo que útil.",
    "🥫 La lata que abriste te mató… moralmente.",
    "💀 Morir es parte del juego… pero tú lo haces artístico.",
    "🏹 Apuntaste bien… para fallar.",
    "🥾 Corres como si tu vida dependiera de ello… y es verdad.",
    "🍗 Esa carne estaba podrida… igual que tu estrategia.",
    "🩸 Sangre por todas partes… menos de los enemigos.",
    "🔪 Ese zombi tenía más vida que tú.",
    "🥫 Abriste una lata… y apareció un jugador.",
    "💀 Sobreviviste un minuto, aplaudamos.",
    "🏹 Flechazo épico… directo a tu destino.",
    "🥾 Corres, tropiezas y mueres… rutina diaria.",
    "🍗 Comer antes de morir es un lujo que nunca tendrás.",
    "🩸 Tu sangre fertiliza el suelo… literalmente.",
    "🔪 Ese cuchillo era de mentira, ¿verdad?",
    "🥫 Abres la lata… y aparece la muerte.",
    "💀 Morir nunca fue tan divertido.",
    "🏹 Flecha perdida… impacta tu moral.",
    "🥾 Sigues corriendo… hacia otro jugador.",
    "🍗 Esa comida durará menos que tu vida.",
    "🩸 Los zombis te saludan mientras mueres.",
    "🔪 Intentaste pelear… te derrotaste a ti mismo.",
    "🥫 Abriste una lata y encontraste tu fin.",
    "💀 Caíste en la trampa… del zombi o del jugador.",
    "🏹 Apuntaste… y fallaste gloriosamente.",
    "🥾 Caminaste hacia la muerte como un héroe absurdo.",
    "🍗 Ese snack duró más que tu paciencia.",
    "🩸 Tu sangre es parte del paisaje ahora.",
    "🔪 Ese cuchillo cortó tu moral, no al enemigo.",
    "🥫 La comida desapareció… y tú también.",
    "💀 Moriste, pero al menos fue memorable.",
    "🏹 Flechazo épico… directo a tu propio pie.",
    "🥾 Corres hacia la muerte… y llegas antes que nadie.",
    "🍗 Esa carne sabía mejor que tu estrategia.",
    "🩸 Cada zombi te recuerda tu incompetencia.",
    "🔪 El cuchillo no sirve, tú lo sabías.",
    "🥫 La lata que abriste… fin de la historia.",
    "💀 Sobrevivir es opcional, morir es obligatorio.",
    "🏹 Apuntaste bien… y fallaste peor.",
    "🥾 Corres como si hubiera esperanza… no la hay.",
    "🍗 Esa comida duró más que tú en combate.",
    "🩸 Tu sangre adorna el mapa del servidor.",
    "🔪 Ese zombi ganó el combate sin esfuerzo.",
    "🥫 Abriste una lata… y el enemigo apareció.",
    "💀 Morir es parte del aprendizaje… aunque no aprendas.",
    "🏹 Flecha disparada… directo a tu muerte.",
    "🥾 Sigues corriendo… directo al respawn.",
    "🍗 Esa comida sabe a derrota y desesperación.",
    "🩸 Cada zombi que pasa ríe de ti.",
    "🔪 Ese cuchillo era inútil desde el inicio.",
    "🥫 La lata que abriste fue tu último acto.",
    "💀 Moriste, pero hiciste historia… la tuya propia.",
    "🏹 Apuntaste… y fallaste estrepitosamente.",
    "🥾 Caminaste hacia tu destino… y llegaste pronto.",
    "🍗 Comer antes de morir es solo un sueño.",
    "🩸 Tu sangre ahora es decoración del mapa."
]
