delta_force_phrases = [
    "🎯 Francotirador tan preciso que solo acierta al aire.",
    "🚁 Helicóptero enemigo avistado… 3 segundos antes de estrellarnos.",
    "🪖 Sigilo nivel experto: lo escucharon hasta en otro servidor.",
    "💥 Granadas lanzadas… a sus propios pies.",
    "📡 Apoyo aéreo pedido… en coordenadas equivocadas.",
    "👀 Invisible como un arbusto en pleno desierto.",
    "🔥 El verdadero arte del fuego amigo en acción.",
    "🏜️ Perdido en el mapa desde hace 20 minutos.",
    "🔫 Ráfaga de balas y ni un rasguño al enemigo.",
    "🕵️ Camper tan quieto que lo confundieron con decoración.",
    "💣 Lanzando bombas… sobre nuestro propio campamento.",
    "🚶 Corriendo al combate… directo a la emboscada.",
    "🛡️ Defendiendo la base como si nadie viniera… y todos vinieron.",
    "🎯 Disparo perfecto… a nuestro compañero.",
    "🚁 Helicóptero destruido por… tu propia torpeza.",
    "🪖 Sigilo de ninja… detectado por un perro enemigo.",
    "💥 Granadas mágicas: desaparecen y revientan en tu mochila.",
    "📡 Pedido de refuerzos… recibimos memes en su lugar.",
    "👀 Tan camuflado que ni tú te encuentras.",
    "🔥 Incendio controlado… en nuestro vehículo.",
    "🏜️ Perdidos otra vez… GPS roto y brújula invertida.",
    "🔫 Balas desperdiciadas… y aún nos preguntamos por qué.",
    "🕵️ Camper nivel dios… pero olvidó recargar.",
    "💣 La explosión fue… una fiesta para los enemigos.",
    "🚶 Corriendo como héroe… directo al respawn.",
    "🛡️ Protegiendo la bandera… que ya habían capturado.",
    "🎯 Francotirador invisible… que solo dispara al suelo.",
    "🚁 Helicóptero amigo destruido por fuego amigo, obviamente.",
    "🪖 Sigilo absoluto… detectado por la luz del sol.",
    "💥 Granadas lanzadas… a tu propio escuadrón.",
    "📡 Apoyo aéreo pedido… recibimos saludos de los enemigos.",
    "👀 Invisible y completamente inútil.",
    "🔥 Quemando todo… menos al enemigo.",
    "🏜️ Perdidos desde el amanecer hasta el atardecer.",
    "🔫 Disparando al enemigo… pero fallando épicamente.",
    "🕵️ Camper con cobertura… que olvidó mirar.",
    "💣 Explosión controlada… y de paso destruí tu arma.",
    "🚶 Corriendo con estilo… directo a la muerte.",
    "🛡️ Defendiendo… mientras todos nos flanquean.",
    "🎯 Disparo certero… en tu propio pie.",
    "🚁 Helicóptero derribado… por nuestra incompetencia.",
    "🪖 Sigilo avanzado… detectado por un zángano.",
    "💥 Granadas lanzadas… dentro de nuestra base.",
    "📡 Apoyo aéreo pedido… y nos lanzaron confeti.",
    "👀 Invisible, pero con brillos fluorescentes.",
    "🔥 Fuego amigo nivel experto.",
    "🏜️ Perdidos otra vez… mapa invertido.",
    "🔫 Disparando a todo… excepto al enemigo.",
    "🕵️ Camper detectado… por un conejo.",
    "💣 La granada fue a parar… a tu cara.",
    "🚶 Corriendo al combate… directo a la trampa.",
    "🛡️ Defendiendo… pero sin balas.",
    "🎯 Francotirador fallido… ni rozó al enemigo.",
    "🚁 Helicóptero amigo destruido por un misil amigo.",
    "🪖 Sigilo perfecto… hasta que tropiezas.",
    "💥 Granadas explosivas… en tu mochila.",
    "📡 Pedido de apoyo… recibido: burlas enemigas.",
    "👀 Invisible, pero haciendo ruido como un elefante.",
    "🔥 Incendio en el campamento… gracias a ti.",
    "🏜️ Perdidos en el desierto… sin agua ni sentido.",
    "🔫 Ráfagas inútiles… y enemigos riendo.",
    "🕵️ Camper olvidó la munición.",
    "💣 Explosión épica… y tú en el centro.",
    "🚶 Corriendo al destino… que ya no existe.",
    "🛡️ Protegiendo la bandera… mientras huimos.",
    "🎯 Disparo preciso… en nuestro propio tanque.",
    "🚁 Helicóptero amigo destruido… otra vez.",
    "🪖 Sigilo fallido… detectado por un pájaro.",
    "💥 Granadas lanzadas… al aire sin control.",
    "📡 Apoyo aéreo… llegó tarde, como siempre.",
    "👀 Invisible, pero todos saben dónde estás.",
    "🔥 Quemando todo… excepto lo que debías.",
    "🏜️ Perdidos en el mapa… pero bien vestidos.",
    "🔫 Disparos al azar… y nadie muere.",
    "🕵️ Camper descubierto… por un arbusto.",
    "💣 La granada explotó… en tu propio escuadrón.",
    "🚶 Corriendo al respawn… sin escalas.",
    "🛡️ Defendiendo la base… solo con palabras.",
    "🎯 Francotirador que dispara… a la nada.",
    "🚁 Helicóptero destruido por error humano.",
    "🪖 Sigilo absoluto… detectado por la sombra.",
    "💥 Granadas lanzadas… y fallaste todos los tiros.",
    "📡 Apoyo aéreo pedido… llegaron memes enemigos.",
    "👀 Invisible, pero brillas más que el sol.",
    "🔥 Incendio accidental… gracias a tu genio.",
    "🏜️ Perdidos otra vez… sin mapa ni idea.",
    "🔫 Disparos sin puntería… épico fracaso.",
    "🕵️ Camper olvidó moverse… y murió.",
    "💣 Explosión en tu cara… sorpresa total.",
    "🚶 Corriendo hacia la muerte… con gracia.",
    "🛡️ Protegiendo la bandera… mientras nos masacran.",
    "🎯 Disparo perfecto… directo a nuestro tanque.",
    "🚁 Helicóptero amigo derribado… otra vez.",
    "🪖 Sigilo máximo… detectado por un zombi.",
    "💥 Granadas fallidas… en tu mochila.",
    "📡 Apoyo aéreo… que llegó tarde y mal.",
    "👀 Invisible, pero totalmente inútil.",
    "🔥 Quemando todo… excepto al enemigo.",
    "🏜️ Perdidos en el desierto… sin rumbo ni esperanza.",
    "🔫 Balas al azar… y todos sobreviven."
]
