ets2_phrases = [
    "🚚 Un café, un camión y 12 horas de carretera virtual.",
    "🛑 Cuidado con los radares, que aquí también multan.",
    "🎶 No es Euro Truck, es Euro Disco Simulator con tanta radio.",
    "🛣️ Curvas imposibles y semáforos estratégicamente colocados para arruinar tu día.",
    "📦 Cargando palets imaginarios… y todavía llego tarde.",
    "⛽ Parada técnica… otra vez olvidé repostar.",
    "🚦 Semáforos que cambian solo para arruinar tu racha perfecta.",
    "💤 Dormir al volante no es opcional… hasta que te despiertan los aliens de GPS.",
    "📏 Señales de tráfico que parecen un test de paciencia.",
    "🛻 Adelantando camiones imaginarios con estilo.",
    "🎧 Playlist de radio… 90% publicidad, 10% música épica.",
    "🚚 El camión va bien… hasta que aparece un conejo en la carretera.",
    "🛑 Radar en cada curva… ¿alguien contrató a estos sadistas?",
    "📦 Palets que pesan más que tu autoestima.",
    "⛽ Repostar en autopistas… nivel: supervivencia.",
    "🛣️ Carreteras infinitas… y tú sin GPS.",
    "🚦 Semáforos inteligentes, humanos tontos.",
    "💤 Dormir al volante: el simulador de riesgo extremo.",
    "📏 Señales confusas… te hacen dudar de tu existencia.",
    "🛻 Adelantando camiones… y la policía fantasma te sigue.",
    "🎧 Radio a tope… y anuncios que duran más que tu viaje.",
    "🚚 El camión vibra… como tu paciencia con los clientes.",
    "🛑 Radar a la vista… tu cartera ya tiembla.",
    "📦 Palets caídos… culpa del viento y del universo.",
    "⛽ Combustible crítico… y estás a 10 km de la próxima gasolinera.",
    "🛣️ Carreteras con curvas imposibles… nivel dios requerido.",
    "🚦 Semáforos traicioneros… te pillan siempre.",
    "💤 Dormir mientras conduces… versión hardcore.",
    "📏 Señales raras… ¿camino o laberinto?",
    "🛻 Adelantando al camión del jefe… sin comentarios.",
    "🎧 Radio simulador… anuncios incluidos gratis.",
    "🚚 Camión lleno… pero tu paciencia vacía.",
    "🛑 Radar sorpresa… multa instantánea.",
    "📦 Palets que desaparecen… culpa de los fantasmas.",
    "⛽ Tanque lleno… de preocupaciones.",
    "🛣️ Ruta infinita… y tráfico de NPC’s suicidas.",
    "🚦 Semáforos sincronizados… para frustrarte.",
    "💤 Dormir no recomendado… pero es opcional.",
    "📏 Señales que parecen jeroglíficos egipcios.",
    "🛻 Adelantando como si tuvieras prisa… que la tienes.",
    "🎧 Radio simulador… mezclando éxitos y drama.",
    "🚚 Camión impecable… hasta que aparece un charco.",
    "🛑 Radar escondido… nivel ninja.",
    "📦 Palets apilados como tu estrés.",
    "⛽ Gasolina crítica… y autopista infinita.",
    "🛣️ Curvas imposibles… y tu café derramado.",
    "🚦 Semáforos estratégicamente diseñados para tu frustración.",
    "💤 Dormir o morir… la regla no escrita.",
    "📏 Señales absurdas… pero te hacen sentir inteligente.",
    "🛻 Adelantando con estilo… y esperanza.",
    "🎧 Radio a todo volumen… para olvidar la realidad.",
    "🚚 Camión cargado… pero el GPS te odia.",
    "🛑 Radar traicionero… tu saldo bancario lo confirma.",
    "📦 Palets rebeldes… nunca cooperan.",
    "⛽ Combustible crítico… y no hay gasolinera a la vista.",
    "🛣️ Carreteras eternas… y tu paciencia también.",
    "🚦 Semáforos que solo cambian para ti.",
    "💤 Dormir no recomendado… pero inevitable.",
    "📏 Señales confusas… y tú perdido otra vez.",
    "🛻 Adelantando camiones… y el tráfico se ríe.",
    "🎧 Playlist épica… hasta que suena un anuncio.",
    "🚚 Camión en perfecto estado… hasta el próximo giro.",
    "🛑 Radar oculto… siempre funciona.",
    "📦 Palets mágicos… desaparecen sin avisar.",
    "⛽ Gasolina insuficiente… estrés garantizado.",
    "🛣️ Curvas imposibles… y GPS traicionero.",
    "🚦 Semáforos que juegan contigo.",
    "💤 Dormir mientras conduces… versión extrema.",
    "📏 Señales raras… para desafiar tu mente.",
    "🛻 Adelantando… y el tráfico dice hola.",
    "🎧 Radio simulador… mezclando épico y absurdo.",
    "🚚 Camión impecable… hasta la próxima curva.",
    "🛑 Radar sorpresa… nivel maestro.",
    "📦 Palets rebeldes… siempre culpables.",
    "⛽ Combustible crítico… y carretera infinita.",
    "🛣️ Carreteras infinitas… y semáforos crueles.",
    "🚦 Semáforos sincronizados… para molestarte.",
    "💤 Dormir no opcional… pero divertido.",
    "📏 Señales absurdas… nivel experto.",
    "🛻 Adelantando camiones… estilo libre.",
    "🎧 Radio y drama… combinación perfecta.",
    "🚚 Camión cargado… paciencia vacía.",
    "🛑 Radar escondido… tu cartera tiembla.",
    "📦 Palets caóticos… culpa de tu jefe.",
    "⛽ Tanque crítico… adrenalina incluida.",
    "🛣️ Curvas imposibles… GPS en shock.",
    "🚦 Semáforos estratégicos… nivel demoníaco.",
    "💤 Dormir o morir… regla simulador.",
    "📏 Señales raras… mente confusa.",
    "🛻 Adelantando con estilo… y suerte.",
    "🎧 Radio épica… con drama gratuito.",
    "🚚 Camión perfecto… hasta el próximo charco."
]
