star_citizen_phrases = [
    "🚀 En Star Citizen, los bugs son una característica, no un error.",
    "🌌 Perderse en el espacio es más fácil que encontrar FPS estables.",
    "💸 Cada nave es más cara que el setup del streamer.",
    "🛸 Pilotando a ciegas porque los radares dicen cosas aleatorias.",
    "💥 Explosiones inesperadas… y tu nave también.",
    "👽 Encuentros alienígenas que son más confusos que útiles.",
    "🪐 Viajes interestelares de horas para aterrizar en la misma estación.",
    "🔧 Reparaciones que cuestan más que la nave misma.",
    "📦 Misiones de entrega… que terminan en agujeros negros.",
    "⚠️ Alertas de colisión… pero nadie sabe con qué.",
    "🛠️ Actualizaciones que rompen más de lo que arreglan.",
    "🎮 Jugadores perdidos en el espacio… nivel experto.",
    "💣 Torpedos que explotan en tu cara… otra vez.",
    "👀 Te persigue un NPC… y tú también te persigues a ti mismo.",
    "🌌 Saltos cuánticos que te llevan al sistema equivocado.",
    "🛸 Naves flotando… porque la gravedad decidió no funcionar.",
    "💵 Comprar una nave: sueño; repararla: pesadilla.",
    "🚀 Vuelo sin control… estilo Star Citizen.",
    "🪐 Estaciones espaciales cerradas… porque sí.",
    "💥 Combates épicos… y te quedas sin munición.",
    "👽 Encuentros misteriosos… nadie sabe qué hacer.",
    "📡 Señales perdidas… y comunicación inexistente.",
    "🛠️ Soporte técnico: ignorado por el universo.",
    "🎮 FPS que bajan mientras tu nave acelera.",
    "⚠️ Alarmas infinitas… y ninguna útil.",
    "🛸 Maniobras imposibles… pero todo es legal en el espacio.",
    "💣 Explosiones creativas… en tu propia nave.",
    "🪐 Objetivos imposibles… y nadie reclama.",
    "👀 NPCs que te atacan… sin razón aparente.",
    "💸 Cada actualización: promesa de mejoras, realidad desastre.",
    "🚀 Salto al hiperespacio… a la velocidad de la lentitud.",
    "🛠️ Reparaciones infinitas… que nunca acaban.",
    "🎮 Misiones cooperativas… caos absoluto.",
    "💥 Colisiones con asteroides… porque el espacio es cruel.",
    "👽 Alienígenas confundidos… igual que tú.",
    "🪐 Planetas hermosos… pero inalcanzables.",
    "🛸 Naves voladoras… pero solo en sueños.",
    "⚠️ Advertencias constantes… ignoradas como siempre.",
    "💣 Explosiones en bucle… diversión asegurada.",
    "🎮 Controles difíciles… pero la inmersión es total.",
    "📦 Carga perdida… y nadie sabe dónde.",
    "💸 Comprar munición cuesta más que una nave.",
    "👀 NPCs que hacen teatro… y tú eres el público.",
    "🛠️ Mejoras de nave… que rompen otras partes.",
    "🚀 Despegue complicado… aterrizaje imposible.",
    "🪐 Saltos cuánticos aleatorios… emoción garantizada.",
    "💥 Combates espaciales… estilo caos absoluto.",
    "👽 Encuentros alienígenas… nivel absurdo.",
    "🛸 Pilotaje perfecto… solo en teoría.",
    "💸 Naves caras… explosiones baratas.",
    "🎮 Multiplayer lleno de trolls… diversión asegurada.",
    "⚠️ Alarmas inútiles… estilo SC.",
    "🪐 Objetivos interminables… paciencia opcional.",
    "💣 Torpedos que nunca alcanzan… ni tú tampoco.",
    "👀 NPCs invisibles… o solo imaginación.",
    "🚀 Estacionamiento espacial: misión imposible.",
    "🛠️ Reparaciones constantes… nivel profesional.",
    "🎮 Mapa infinito… y tú perdido en él.",
    "💥 Combates descoordinados… pero épicos.",
    "🪐 Viajes interestelares… sin sentido práctico.",
    "👽 Encuentros aleatorios… caos garantizado.",
    "🛸 Nave dañada… y nadie viene a ayudarte.",
    "💸 Cada reparación: dolor financiero.",
    "🎮 Pilotos novatos… caos asegurado.",
    "⚠️ Advertencias de colisión… ignoradas por todos.",
    "💣 Explosiones improvisadas… diversión garantizada.",
    "👀 NPCs raros… comportamiento inesperado.",
    "🛠️ Mejoras inútiles… estilo SC.",
    "🚀 Despegues épicos… aterrizajes trágicos.",
    "🪐 Planetas hermosos… imposibles de explorar.",
    "💥 Combates fallidos… humor asegurado.",
    "👽 Alienígenas confusos… igual que tú.",
    "🛸 Nave perdida… misterio absoluto.",
    "💸 Cada nueva nave: ruina garantizada.",
    "🎮 Multiplayer caótico… estilo SC.",
    "⚠️ Alarmas por todas partes… ignoradas siempre.",
    "🪐 Misiones interminables… paciencia opcional.",
    "💣 Torpedos que nunca impactan… caos garantizado.",
    "👀 NPCs que desaparecen… misterio espacial.",
    "🛠️ Reparaciones eternas… nivel experto.",
    "🚀 Vuelo complicado… aterrizaje imposible.",
    "💥 Combates absurdos… diversión asegurada.",
    "🪐 Saltos aleatorios… caos máximo.",
    "👽 Encuentros extraños… nivel extremo.",
    "🛸 Pilotaje imposible… experiencia garantizada.",
    "💸 Naves caras… explosiones baratas.",
    "🎮 Jugadores novatos… diversión asegurada.",
    "⚠️ Alertas inútiles… estilo SC.",
    "💣 Explosiones creativas… caos absoluto.",
    "👀 NPCs raros… comportamiento inesperado.",
    "🛠️ Mejoras que rompen otras partes… caos asegurado.",
    "🚀 Despegue épico… aterrizaje trágico.",
    "🪐 Planetas hermosos… pero inalcanzables.",
    "💥 Combates fallidos… risas garantizadas.",
    "👽 Alienígenas confusos… igual que tu nave.",
    "🛸 Nave perdida… caos total.",
    "💸 Cada nave nueva: ruina asegurada.",
    "🎮 Multiplayer lleno de sorpresas… y frustraciones.",
    "⚠️ Alarmas constantes… ignoradas por todos.",
    "🪐 Misiones largas… paciencia opcional.",
    "💣 Torpedos fallidos… diversión asegurada.",
    "👀 NPCs desapareciendo… misterio infinito.",
    "🛠️ Reparaciones eternas… nivel experto.",
    "🚀 Vuelo épico… aterrizaje imposible."
]
