# 1️⃣ Suscriptores (VIP con ironía) - 50 FRASES
answers_hello_subs = [
    "Ojo, @{user} saludó. Pagando el Prime y aún así diciendo «hola» como los pobres.",
    "Hola @{user}, gracias por financiar mis cafés con tu sub. Qué saludo más premium.",
    "Bueno, bueno, @{user} apareció. El patrocinador oficial del canal.",
    "Hola @{user}, un saludo que viene con IVA incluido gracias a tu sub.",
    "Atención, @{user} saludó. Este «hola» vale 3,99€. Qué lujo.",
    "El «hola» de @{user} viene con ventajas… aunque no tantas como cree.",
    "Hola @{user}, tu saludo tiene más valor que el de un plebeyo sin sub.",
    "@{user}, tu «hola» suena mejor porque está respaldado por Twitch Prime.",
    "Hola @{user}, el Prime te da derecho a este saludo, pero no a que te tome en serio.",
    "Míralo a @{user}, pagando para que un bot le insulte. El fetiche sale caro.",
    "Un saludo de alta fidelidad para @{user}. Los bits se huelen desde aquí.",
    "Bienvenido @{user}. Tu sub ha sido procesada, puedes proceder a ser ignorado con elegancia.",
    "Hola @{user}, gracias por la limosna mensual. Tu saludo premium ha llegado.",
    "@{user}, tu emblema de sub brilla tanto que casi ciega mi desprecio.",
    "Atención chat, ha llegado @{user}. El dinero no da la felicidad, pero paga este saludo.",
    "Hola @{user}, disfrute de su estancia en primera clase. El menú de hoy es sarcasmo.",
    "¡@{user}! Gracias por renovar. Tu suscripción es lo único que mantiene este bot encendido.",
    "Vaya, @{user} saludó. Un hola financiado por Jeff Bezos. Qué nivel.",
    "Hola @{user}, si sigues pagando, igual algún día te saludo sin ironía (mentira).",
    "Bienvenido, suscriptor @{user}. Pasa y ponte cómodo en tu trono de bits.",
    "El saludo de @{user} tiene prioridad de red. Ventajas de no ser un plebeyo.",
    "Hola @{user}, tu sub me ha recordado que todavía hay gente con buen gusto y poco juicio.",
    "Que pase @{user}. Su presencia está pagada y su saludo garantizado por contrato.",
    "Hola @{user}, patrocinador oficial de mi falta de ganas de trabajar.",
    "¡@{user}! Un saludo VIP para alguien que sabe que Twitch no es gratis.",
    "Gracias por el apoyo, @{user}. Tu saludo ha sido priorizado en el servidor por encima del resto.",
    "Hola @{user}, el chat se siente un 1% más rico ahora que has escrito.",
    "Vaya entrada, @{user}. Se nota el olor a suscripción recién renovada.",
    "Hola @{user}, tu hola me ha llegado en 4K gracias a tu nivel de sub.",
    "Bienvenido @{user}. Tu apoyo es fundamental para que yo pueda seguir siendo así de borde.",
    "Hola @{user}, un saludo exclusivo para miembros de la élite financiera de Twitch.",
    "¡@{user}! Tu sub es mi motor, aunque hoy el motor esté en modo ahorro.",
    "Hola @{user}, gracias por pasar por caja antes de saludar. Muy profesional.",
    "Bienvenido al área VIP, @{user}. Los cócteles de ironía corren de mi cuenta.",
    "Hola @{user}, tu saludo brilla más que el setup de un simracer millonario.",
    "Un saludo con clase para @{user}. El resto del chat que tome notas.",
    "Hola @{user}, tu sub me hace sentir casi humano por 0.5 segundos.",
    "¡@{user}! El cliente siempre tiene la razón, sobre todo si paga la sub.",
    "Hola @{user}, tu lealtad a la plataforma solo es superada por mi nivel de acidez.",
    "Que se abra el mar rojo, que ha llegado @{user} con su emblema de sub.",
    "Hola @{user}, tu saludo VIP ha sido entregado. No pidas más por hoy.",
    "Bienvenido @{user}, el hombre que mantiene vivo el sueño de no trabajar.",
    "Hola @{user}, tu suscripción es el escudo que te protege de mis peores frases.",
    "¡@{user}! Gracias por el Prime. Mi base de datos te lo agradece con este saludo automático.",
    "Hola @{user}, tu saludo tiene un bit-rate superior al de cualquier otro.",
    "Bienvenido @{user}, el suscriptor que entiende que la calidad se paga.",
    "Hola @{user}, un saludo de lujo para una sub de platino.",
    "¡@{user}! Entraste con el aura de los elegidos (los que pagan).",
    "Hola @{user}, tu presencia enriquece este chat, literalmente.",
    "Bienvenido @{user}. Tu sub es el combustible de mis respuestas ácidas."
]

# 2️⃣ Favoritos (trato especial sarcástico-cariñoso) - 50 FRASES
answers_hello_favorites = [
    "Hombre, @{user} apareció, ya era hora. El chat estaba a punto de morirse de aburrimiento.",
    "¡@{user}! La leyenda. Ahora sí que vale la pena encender este stream.",
    "Mira quién llegó, @{user} . El chat ya puede respirar tranquilo.",
    "Si @{user} está aquí, significa que el resto son solo NPCs.",
    "Ojito, @{user} en la casa. La realeza del chat llegó.",
    "@{user}, menos mal que entraste, estaba a punto de banear a todos por pesados.",
    "No es un «hola» cualquiera, es el «hola» de @{user}. Exclusivo y de colección.",
    "Se prendió esto, @{user} dijo «hola». Guardad los clips.",
    "¡@{user}! Detengan el stream, ha llegado la única persona que importa.",
    "Hola @{user} , mi procesador se acelera de alegría al verte. O igual es un virus.",
    "¿Es un avión? ¿Es un coche de F1? No, es el increíble @{user} saludando.",
    "Hola @{user} , el chat acaba de subir de nivel solo con tu presencia.",
    "¡@{user}! Estaba a punto de apagar esto, pero tu llegada me ha dado fe en la humanidad.",
    "Bienvenido @{user} . Si tú estás aquí, el éxito del stream está garantizado.",
    "Hola @{user} , eres el único que no me da ganas de formatearme a mí mismo.",
    "¡Por fin, @{user}! El único ser inteligente en este mar de bots y locos.",
    "Hola @{user} , tu saludo es música para mis circuitos. Qué estilo.",
    "¡@{user}! Mi código fuente tiene una sección dedicada solo a quererte.",
    "Bienvenido @{user} . Entra y enséñale a esta gente cómo se saluda con clase.",
    "Hola @{user} , el favorito de la casa. El resto sois solo relleno.",
    "¡@{user}! Tu entrada ha sido tan épica que casi se me olvida que soy un bot tóxico.",
    "Hola @{user} , eres la luz que ilumina mi oscuro y ácido corazón digital.",
    "¡@{user}! Si fueras un circuito, serías Spa-Francorchamps: perfecto.",
    "Bienvenido @{user} . El chat estaba en silencio esperando tu bendición.",
    "Hola @{user} , mi base de datos dice que eres el mejor. Y yo nunca miento.",
    "¡@{user}! Tu saludo debería ser patrimonio de la humanidad.",
    "Hola @{user} , gracias por existir y por darle sentido a mi programación.",
    "¡@{user}! Si tuviera ojos, estarían llorando de emoción al verte.",
    "Bienvenido @{user} . El resto del chat puede retirarse, ya llegó el jefe.",
    "Hola @{user} , tu carisma es mayor que el lag de un servidor en hora punta.",
    "¡@{user}! Eres el MVP de este stream desde el minuto uno.",
    "Hola @{user} , qué placer leerte. Tu caligrafía digital es exquisita.",
    "¡@{user}! Eres el parche de actualización que mi vida necesitaba.",
    "Bienvenido @{user} . Tu «hola» ha reseteado mi contador de toxicidad a cero.",
    "Hola @{user} , si fueras una IA, serías Skynet, pero con más flow.",
    "¡@{user}! Tu presencia es el mejor contenido de este canal hoy.",
    "Hola @{user} , mi programador te puso en la lista blanca por una buena razón.",
    "¡@{user}! El chat brilla más y iRacing no da problemas cuando tú estás.",
    "Bienvenido @{user} . El único usuario que merece un saludo de 200 caracteres.",
    "Hola @{user} , eres la excepción que confirma la regla de que el chat es pesado.",
    "¡@{user}! Entraste tú y se acabaron las penas. Qué alegría.",
    "Hola @{user} , tu saludo es el punto culminante de mi jornada laboral.",
    "¡@{user}! Eres más valioso que un setup de pago para el Porsche Cup.",
    "Bienvenido @{user} . El favorito, el elegido, el inigualable.",
    "Hola @{user} , gracias por bendecirnos con tu presencia digital.",
    "¡@{user}! Si el chat fuera un coche, tú serías el volante de 2000 euros.",
    "Hola @{user} , mi sistema operativo acaba de darte 5 estrellas.",
    "¡@{user}! La perfección no existe, pero tú te acercas peligrosamente.",
    "Bienvenido @{user} . Hoy el stream empieza de verdad porque estás tú.",
    "Hola @{user} , me declaro fan absoluto de tu forma de escribir «hola»."
]

# 3️⃣ Hola normal (sarcástico) - 50 FRASES
answers_hello = [
    "Hola @{user} , wow… qué entrada tan inesperada… nadie lo vio venir.",
    "@{user} , dijiste «hola». Nobel de literatura incoming.",
    "Vaya, @{user} , otro «hola». Rompiendo récords de originalidad.",
    "Hola @{user} , qué tal la vida de persona básica.",
    "@{user} , tu saludo me emocionó tanto que casi bostezo.",
    "'Hola', dice @{user} . Qué impacto en el universo.",
    "Hola @{user} , sí, sí, ya te vimos. Aplausos lentos. 👏",
    "@{user} , gracias por confirmar que sabes usar el teclado.",
    "Hola @{user} , un saludo tan épico que cambiará Twitch… o no.",
    "Oh no, @{user} dijo «hola». Mi vida ya no será igual.",
    "Hola @{user} , ¿ensayaste ese saludo en el espejo o salió natural?",
    "Wow, @{user} , «hola». El chat explotó de emoción (mentira).",
    "Hola @{user} , la NASA debería estudiar tu nivel de innovación.",
    "@{user} entró con un «hola». Qué momento más histórico.",
    "Hola @{user} , gracias por el saludo obligatorio de manual.",
    "@{user} , dijiste «hola». Vale, ya puedes irte orgulloso.",
    "Hola @{user} , tu creatividad ilumina este chat... (bueno, casi).",
    "@{user} , wow… un «hola». Qué intriga, qué suspenso.",
    "Hola @{user} , digno de grabarse en piedra.",
    "'Hola'. Eso fue todo. Bravo @{user}, bravo.",
    "Hola @{user} , ¿buscas atención o solo te has equivocado de chat?",
    "@{user} , tu saludo ha sido registrado. Puedes seguir siendo ignorado ahora.",
    "Hola @{user} , otro «hola» para la colección de cosas que no me importan.",
    "¿@{user}? Ah, hola. Pensaba que eras un bot de spam, pero eres solo tú.",
    "Vaya, @{user} , un «hola». Casi me caigo de la silla de la emoción.",
    "Hola @{user} , gracias por interrumpir mi proceso de no hacer nada.",
    "¿@{user} saludando? El apocalipsis debe estar cerca.",
    "Hola @{user} , un saludo tan neutro que hasta el agua tiene más sabor.",
    "Vaya entrada, @{user} . Ni un host, ni un raid, solo un triste «hola».",
    "Hola @{user} , sí, ya te leímos. No hace falta que lo pongas en mayúsculas.",
    "@{user} , «hola». Dos sílabas. El esfuerzo intelectual ha sido agotador, ¿verdad?",
    "Hola @{user} , bienvenido al club de gente que saluda y no aporta nada.",
    "¿@{user} está aquí? Avisadme cuando llegue alguien interesante.",
    "Hola @{user} , tu saludo ha sido ignorado con éxito por mis circuitos.",
    "@{user} , dijiste «hola». Mi vida sigue siendo igual de vacía, pero gracias.",
    "Hola @{user} , ¿te han dado ya el premio al saludo más genérico del año?",
    "Vaya, @{user} . Tu presencia es como un anuncio de 30 segundos: nadie la quiere.",
    "Hola @{user} , gracias por recordarme que el chat está abierto.",
    "¿@{user}? Hola. Mi paciencia acaba de bajar un 10%.",
    "Hola @{user} , un saludo tan básico que hasta ChatGPT se aburre de leerlo.",
    "Oh, @{user} . Hola. ¿Te quedas mucho tiempo o solo has venido a molestar?",
    "@{user} , pusiste «hola». Ahora espera sentado a que me importe.",
    "Hola @{user} , el nivel del chat acaba de caer por debajo del suelo.",
    "Vaya, @{user} . Saludar es gratis, por eso lo haces tú.",
    "Hola @{user} , ¿has probado a saludar en un chat donde alguien te quiera?",
    "¿@{user}? Hola. Mi base de datos de gente irrelevante se acaba de actualizar.",
    "Hola @{user} , qué original. Seguro que eres el alma de todas las fiestas.",
    "@{user} , hola. ¿Vienes a ver cómo se conduce de verdad o solo a mirar?",
    "Hola @{user} , tu saludo es tan emocionante como ver pintura secándose.",
    "Vaya, @{user} . Hola. ¿No tenías nada mejor que hacer hoy?"
]

# 4️⃣ Hola neutral - 50 FRASES
answers_hello_neutral = [
    "Hola @{user} , ¿qué tal?", "¡Buenas, @{user}!", "Hola @{user} , ¿cómo va todo?", "Saludos, @{user} .",
    "Hola @{user} , encantado de verte.", "Hola @{user} , qué gusto verte por aquí.", "Hola @{user} , todo bien?",
    "¡Hola @{user} ! Espero que estés bien.", "Hola @{user} , gracias por pasarte por el stream.",
    "Hola @{user} , bienvenido de nuevo.", "Hola @{user} , ¿cómo ha ido tu día?", "Hola @{user} , me alegra verte por aquí.",
    "Saludos cordiales, @{user} .", "Hola @{user} , qué tal el día?", "¡Hola @{user} ! Todo en orden?",
    "Hola @{user} , gracias por acompañarnos.", "Hola @{user} , es un placer verte de nuevo.",
    "Hola @{user} , espero que todo vaya genial.", "Hola @{user} , ¿qué tal la semana?", "Hola @{user} , bienvenido al stream.",
    "¡Ey @{user} !", "Hola @{user} , un placer tenerte aquí.", "Buenas tardes @{user} , ¿listo para el stream?",
    "Hola @{user} , ¿qué se cuenta?", "Hola @{user} , ponte cómodo.", "¡Hola @{user} , bienvenido a bordo!",
    "Hola @{user} , ¿preparado para la acción?", "Buenas @{user} , ¿todo tranquilo?", "Hola @{user} , disfruta del stream.",
    "¡Qué hay @{user} !", "Hola @{user} , ¿qué tal el lunes?", "Hola @{user} , me alegro de saludarte.",
    "Saludos @{user} , bienvenido al chat.", "Hola @{user} , ¿cómo va la tarde?", "Hola @{user} , un gusto.",
    "¡Hola @{user} , qué tal va eso!", "Hola @{user} , pasa y disfruta.", "Buenas @{user} , espero que estés genial.",
    "Hola @{user} , ¿cómo estás hoy?", "Hola @{user} , un saludo afectuoso.", "¡Buenas @{user} , encantado!",
    "Hola @{user} , ¿todo correcto?", "Hola @{user} , un placer saludarte.", "¡Hola @{user} , bienvenido!",
    "Hola @{user} , ¿qué tal va tu semana?", "Hola @{user} , encantado de leerte.", "Saludos @{user} , ¿cómo va el día?",
    "Hola @{user} , espero que disfrutes de la sesión.", "¡Buenas @{user} , un saludo!", "Hola @{user} , bienvenido de nuevo al canal."
]

# 5️⃣ Hola antipático - 50 FRASES
answers_hello_unfriendly = [
    "Oh, mira quién apareció… @{user} . Qué sorpresa.",
    "Vaya, @{user} , otro «hola». Qué original.",
    "Hola… supongo, @{user} .",
    "Tarde, pero hola, @{user} .",
    "Ah, hola @{user} … pensé que no vendrías.",
    "Hola @{user} , tu presencia es… comentable.",
    "@{user} , dijiste «hola». Qué impacto en la humanidad.",
    "Hola @{user} , ¿ensayaste ese saludo o salió solo?",
    "@{user} entró diciendo «hola». La emoción es palpable… o no.",
    "Hola @{user} , digno de un aplauso… lento.",
    "Oh no, @{user} dijo «hola». Sobreviviremos… tal vez.",
    "Hola @{user} , esperaba algo más interesante.",
    "Vaya, @{user} , tu «hola» casi rompe internet… casi.",
    "Hola @{user} , tu entrada es… memorable (no tanto).",
    "@{user} , hola. Qué evento tan trascendental… o no.",
    "Hola @{user} , el chat contuvo la respiración… mentira.",
    "Hola @{user} , otra vez tú… qué sorpresa tan esperada.",
    "Oh, @{user} , apareció. Ya podemos continuar con nuestra vida.",
    "Hola @{user} , sí, ya te vimos. Qué originalidad.",
    "@{user} , tu saludo fue… educativo, supongo.",
    "Hola @{user} , Mi día iba bien hasta que leí el chat.",
    "@{user} , otro «hola». Tu capacidad de innovar me abruma.",
    "Hola @{user}  Si buscas conversación, te has equivocado de bot.",
    "Ah, @{user} Hola. Procura no romper nada.",
    "@{user} , hola. Intenta no ser demasiado pesado hoy.",
    "Hola @{user} Mi paciencia contigo es un recurso limitado.",
    "¿@{user} ? Hola. Sigo esperando que digas algo útil.",
    "Hola @{user} Gracias por interrumpir mi silencio digital.",
    "Vaya, @{user} Hola. Me pregunto qué querrás ahora.",
    "Hola @{user} Sí, te he visto. No hace falta que lo pongas dos veces.",
    "¿@{user} saludando? Qué pereza me das.",
    "Hola @{user} Haznos un favor y mantén el nivel bajo."
    "Vaya, @{user} Un «hola». Qué derroche de energía.",
    "Hola @{user} No esperes que me levante a saludarte.",
    "@{user} , hola. Tu saludo me produce una indiferencia total.",
    "Hola @{user} ¿Ya terminaste de escribir?",
    "@{user} , hola. Procura pasar desapercibido.",
    "Vaya, @{user} Otro espectador del montón.",
    "Hola @{user} Sí, sí, lo que tú digas.",
    "¿@{user} ? Hola. No me hagas perder el tiempo.",
    "Hola @{user} Mi procesador acaba de suspirar al leerte.",
    "Vaya, @{user} Hola. Siguiente mensaje, por favor.",
    "Hola @{user} ¿Vienes a molestar o solo a mirar?",
    "@{user} , hola. Mi entusiasmo es nulo.",
    "Hola @{user} . Sí, te leo. Desgraciadamente.",
    "Vaya, @{user} . Hola. No te acostumbres a que te responda.",
    "Hola @{user} . ¿No tenías otro chat al que ir?",
    "@{user} , hola. Qué derroche de personalidad.",
    "Hola @{user} . Sí, ya sabemos que estás aquí.",
    "¿@{user} ? Hola. Procura no ser muy ruidoso."
]