X4_PHRASES = [
    "💥 Contacto directo con otro piloto; parece que el asfalto se les ha quedado pequeño a los dos, x4",
    "🚨 Dirección de carrera ya ha tomado nota del número y el color del coche implicado, x4",
    "🤝 Demasiado cariño entre coches; el amor por la trazada a veces acaba en chapa y pintura, x4",
    "📞 Llamada de los comisarios en camino; mejor ve preparando una buena excusa por radio, x4",
    "🚑 Esto ya no era rodar en solitario; ahora hay otro piloto bastante enfadado contigo, x4",
    "💥 Golpe confirmado; el sensor de impactos acaba de despertarse de la peor manera, x4",
    "🚨 Incidente grave que va a dar mucho que hablar en la oficina de los comisarios, x4",
    "🤝 Se tocaron de forma evidente y, sinceramente, no era necesario arriesgar tanto ahí, x4",
    "📉 Error con consecuencias directas en la aerodinámica y en el humor del rival, x4",
    "🚗💥 Contacto totalmente innecesario que podría haberse evitado con un poco de paciencia, x4",
    "⚠️ Eso fue contacto directo y seco; de los que dejan huella en la carrocería, x4",
    "💥 Choque detectado; esperamos que ambos pilotos tengan el seguro de carreras al día, x4",
    "🚨 Dirección de carrera frunce el ceño y ya está revisando todas las cámaras disponibles, x4",
    "🤝 Exceso de confianza compartida: dos coches buscando el mismo vértice al mismo tiempo, x4",
    "📞 Penalización mental en camino; el piloto ya sabe que esto no va a salirle gratis, x4",
    "🚑 Esto ya duele de ver; un impacto que va a obligar a pasar por boxes sí o sí, x4",
    "💥 Toque claro y nítido; se ha escuchado el crujir de la fibra de carbono desde la grada, x4",
    "🚨 Incidente serio que pone en peligro la continuidad de ambos en la carrera, x4",
    "🤝 Dos coches y una muy mala decisión; el resultado es el que todos estamos viendo, x4",
    "📉 Contacto evitable que arruina el trabajo de muchas vueltas en un solo segundo, x4",
    "🚗💥 Demasiado cerca como para no acabar compartiendo pintura y piezas de repuesto, x4",
    "⚠️ Golpe entre pilotos de los que suelen terminar con una bandera de sanción, x4",
    "💥 Impacto confirmado; la suspensión acaba de recibir un mensaje que no le va a gustar, x4",
    "🚨 Los comisarios acaban de despertar y ya están afilando el lápiz para el informe, x4",
    "🤝 Amor racing no correspondido; uno quería pasar y el otro no quería dejarle sitio, x4",
    "📞 Informe redactándose en tiempo real; esto huele a investigación post-carrera, x4",
    "🚑 Esto no eran hotlaps de clasificación; aquí hay tráfico y hay que respetarlo, x4",
    "💥 Toque feo que deja claro quién ha perdido los nervios en la frenada, x4",
    "🚨 Bandera amarilla mental para el piloto; es hora de enfriar la cabeza antes del próximo giro, x4",
    "🤝 Contacto innecesario provocado por un ansia excesiva de ganar la posición, x4",
    "📉 Error caro que probablemente acabe con una visita inesperada al muro de boxes, x4",
    "🚗💥 Choque evitable si alguien hubiera levantado el pie del acelerador a tiempo, x4",
    "⚠️ Eso ya no es casualidad; hay demasiada agresividad acumulada en ese morro, x4",
    "💥 Golpe serio que ha hecho que el coche del rival parezca un acordeón, x4",
    "🚨 Dirección de carrera observa atentamente cada repetición desde todos los ángulos, x4",
    "🤝 Dos coches y cero paciencia; la fórmula matemática perfecta para el desastre, x4",
    "📞 Incidente bajo revisión oficial; mantén la calma mientras deciden tu destino, x4",
    "🚑 Esto va directo al replay de los momentos más accidentados de la jornada, x4",
    "💥 Contacto directo; el piloto ha confundido el coche de delante con un parachoques, x4",
    "🚨 Penalización moral aplicada; el respeto en pista acaba de bajar varios puntos, x4",
    "🤝 Mucha cercanía y muy poco espacio; las leyes de la física no perdonan estos lujos, x4",
    "📉 Error compartido donde nadie quiso ceder y al final ambos salieron perdiendo, x4",
    "🚗💥 Golpe innecesario que deja el coche con una geometría de dirección creativa, x4",
    "⚠️ Contacto peligroso que ha estado a punto de terminar en un vuelo sin motor, x4",
    "💥 Impacto claro; los mecánicos ya están preparando la cinta americana en el garaje, x4",
    "🚨 Los comisarios están tomando café, pero ni por esas se les ha escapado este toque, x4",
    "🤝 Racing incident… o eso intentará explicar el piloto cuando le pregunten, x4",
    "📞 Esto acaba en protesta formal; se masca la tragedia en el paddock tras este golpe, x4",
    "🚑 Bandera amarilla mental; el coche está tocado y el orgullo del piloto también, x4",
]