gta_v_rp_phrases = [
    "🚓 Roleplay de GTA: donde todos son policías o mafiosos.",
    "💵 Dinero virtual, pero estrés muy real.",
    "😂 Ese rol tiene menos sentido que la trama de Fast & Furious.",
    "🏦 Robos planificados… que siempre salen mal.",
    "👮‍♂️ Policía corrupto, jugador honesto… qué sorpresa.",
    "🛵 Conduciendo por la ciudad como si fuera una autopista de locos.",
    "💣 Explosiones al azar, pero culpa del juego, claro.",
    "🏎️ Carreras ilegales y multas imaginarias.",
    "🎭 Actuación dramática… pero nadie sigue las reglas.",
    "📱 Mensajes de emergencia que nadie lee.",
    "🚨 Alarmas que suenan por cualquier tontería.",
    "💰 Dinero robado que desaparece misteriosamente.",
    "👊 Peleas de RP que terminan en memes.",
    "🛑 Semáforos que nadie respeta… en serio.",
    "🏙️ Ciudad abierta… caos garantizado.",
    "🪪 Identidades falsas y dramas épicos.",
    "🔫 Armas en cada esquina, pero nadie acierta.",
    "📦 Misiones de entrega que terminan en desastre.",
    "🚗 Vehículos robados… y luego olvidados.",
    "🎶 Radio a todo volumen… y nadie escucha.",
    "🕵️ Intriga y traición… versión GTA RP.",
    "💤 Dormir es opcional… y mortal.",
    "👀 Miradas sospechosas… sin motivo alguno.",
    "🧨 Granadas lanzadas… por error, siempre.",
    "🏭 Trabajo legal… si ignoras los robos diarios.",
    "💸 Lobby virtual lleno de estafadores expertos.",
    "🛠️ Reparaciones… que solo empeoran el problema.",
    "📡 Comunicaciones interrumpidas por jugadores trolls.",
    "🎭 Eventos RP que nadie sigue como toca.",
    "🛣️ Tráfico caótico… y policía invisible.",
    "💣 Explosiones de coches por diversión.",
    "🏃‍♂️ Corriendo de la ley… y del sentido común.",
    "💵 Billetes volando… como tus expectativas.",
    "🚔 Policía lenta… y criminales rápidos.",
    "👑 Cada jugador se cree el jefe.",
    "📦 Paquetes misteriosos… con consecuencias absurdas.",
    "🕹️ Controles difíciles… pero el caos fácil.",
    "🚨 Emergencias inventadas… todo el tiempo.",
    "🛵 Conducción creativa… ilegal por definición.",
    "💬 Diálogos dramáticos… con emojis incluidos.",
    "🎶 Música intensa… para momentos ridículos.",
    "🔫 Balas perdidas… pero siempre dramáticas.",
    "🏙️ Ciudad viva… aunque nadie siga la vida real.",
    "🪪 Identidades cambiantes… confusión máxima.",
    "💤 Dormir y soñar… que es más seguro.",
    "💣 Fuegos artificiales… o explosiones de caos.",
    "🛑 Semáforos ignorados… estilo RP.",
    "👊 Peleas absurdas… con reglas flexibles.",
    "🚗 Vehículos abandonados… y robados otra vez.",
    "🎭 Drama garantizado… por cualquier motivo.",
    "🏦 Banco virtual… problemas reales.",
    "📱 Mensajes ignorados… consecuencias épicas.",
    "🕵️ Sospechas sin fundamento… drama asegurado.",
    "💸 Dinero virtual que desaparece misteriosamente.",
    "🚨 Alarmas activadas… sin razón alguna.",
    "🛣️ Carreteras locas… jugadores locos.",
    "🧨 Explosiones que nadie pidió.",
    "💵 Transacciones absurdas… sin sentido.",
    "🪪 Roles cambiantes… caos total.",
    "🎶 Radio a tope… jugadores distraídos.",
    "🏎️ Carreras ridículas… y accidentes creativos.",
    "👀 Miradas dramáticas… por nada.",
    "💤 Dormir opcional… peligro asegurado.",
    "💣 Granadas accidentales… siempre presentes.",
    "🚔 Policía lenta… y criminales creativos.",
    "🛠️ Reparaciones inútiles… desastre total.",
    "📡 Comunicación rota… drama épico.",
    "🏭 Trabajo legal… imposible de seguir.",
    "💬 Conversaciones épicas… con errores ridículos.",
    "🚗 Vehículos descontrolados… caos seguro.",
    "🎭 Eventos RP… nadie respeta.",
    "🕹️ Controles locos… jugadores más locos.",
    "💸 Dinero fácil… problemas difíciles.",
    "🛵 Conducción creativa… sin reglas.",
    "🏙️ Ciudad llena de historias absurdas.",
    "👑 Cada jugador cree ser el protagonista.",
    "💣 Explosiones casuales… diversión asegurada.",
    "🚨 Emergencias inventadas… caos total.",
    "🪪 Identidades falsas… drama máximo.",
    "🎶 Música intensa… para momentos ridículos.",
    "🛑 Semáforos ignorados… estilo libre.",
    "🏦 Banco lleno de trolls… paciencia cero.",
    "🕵️ Sospechas absurdas… conflictos épicos.",
    "🚔 Policía lenta… caos garantizado.",
    "👊 Peleas sin sentido… emoción incluida.",
    "🏎️ Carreras peligrosas… adrenalina virtual.",
    "💤 Dormir… riesgo mortal.",
    "📦 Paquetes misteriosos… problemas asegurados.",
    "🛠️ Reparaciones inútiles… desastre garantizado.",
    "💬 Diálogos exagerados… risa asegurada.",
    "🧨 Explosiones creativas… desastre total.",
    "🚗 Vehículos fuera de control… diversión máxima.",
    "🎭 Drama constante… nunca falta acción.",
    "💵 Dinero virtual… estrés real.",
    "🔫 Balas perdidas… caos inevitable.",
    "🏙️ Ciudad viva… sin sentido pero entretenida.",
    "🪪 Identidades cambiantes… confusión garantizada.",
    "🎶 Radio alta… para momentos épicos.",
    "💣 Fuegos artificiales o caos… depende del día.",
    "🛑 Semáforos… solo decoración.",
    "🕹️ Controles imposibles… diversión asegurada."
]
