iracing_phrases = [
        "iRacing: para los que saben que el realismo no se compra en Steam en oferta.",
        "Otros simus tienen físicas tan falsas que Fast & Furious parece un documental.",
        "Juegas a Gran Turismo, qué bien... ¿y cuándo aprendes a frenar sin ABS?",
        "Assetto Corsa es genial... si te gusta conducir sobre mantequilla.",
        "Project Cars 2: cuando quieres simular cómo NO se comporta un coche.",
        "Si tus ruedas en F1 23 parecen globos, es porque lo son.",
        "En iRacing los errores se pagan caros, en otros... los reinicias como si nada.",
        "Los que juegan a ACC y presumen de física no han probado las salidas en lluvia en iRacing.",
        "Forza: donde el drift es automático y el realismo es opcional.",
        "iRacing es tan real que lloras cuando te comes un muro.",
        "iRacing no tiene modo arcade porque no insulta tu inteligencia.",
        "¿Te gusta la simulación? Entonces deja el mando y toca un volante en serio.",
        "Frenar en iRacing es una ciencia. En otros, es presionar cuadrado y rezar.",
        "iRacing no tiene rewind, porque la vida real tampoco.",
        "Otros juegos simulan coches. iRacing simula consecuencias.",
        "En otros simus puedes chocar y seguir. En iRacing aprendes a tener respeto.",
        "iRacing: donde cada curva puede ser tu última si eres un burro.",
        "F1 23 tiene flashes de realismo. iRacing tiene dolor constante.",
        "¿ACC? Está bien… para aprender lo que no debes hacer en iRacing.",
        "Los pilotos de verdad usan iRacing. Los demás usan filtros de Instagram.",
        "iRacing no es bonito, es brutalmente honesto.",
        "En Forza puedes pintar el coche. En iRacing puedes perder tu licencia.",
        "iRacing no te aplaude por acabar último, te baja de categoría.",
        "En otros juegos corres. En iRacing sobrevives.",
        "El matchmaking de iRacing no es para blandos. Aquí te destruyen con educación.",
        "¿Te gusta resetear después de un error? Entonces no es iRacing.",
        "La comunidad de iRacing insulta con clase. En otros, con emojis.",
        "iRacing: donde cada sesión parece un examen final.",
        "iRacing no es divertido. Es adictivo, frustrante y glorioso.",
        "Cuando pruebas iRacing, los demás te parecen Mario Kart con esteroides.",
        "iRacing no te perdona, pero sí te enseña.",
        "Otros simulan coches. iRacing simula decisiones malas.",
        "ACC brilla en gráficos. iRacing brilla cuando lo sientes en el volante.",
        "Forza es para hacer donuts. iRacing para que te dé un infarto en Spa.",
        "iRacing: porque la curva de aprendizaje es una pared vertical.",
        "iRacing es como el Dark Souls de los simuladores. Sin guía, sin compasión.",
        "Jugar a iRacing es como trabajar de piloto sin sueldo.",
        "Otros tienen gráficos. iRacing tiene física y estrés postraumático.",
        "iRacing: donde aprender a hacer un pit stop vale más que 10 campeonatos en F1 23.",
        "¿Lag en otros juegos? En iRacing eso es sentencia de muerte.",
        "En ACC puedes hacer locuras. En iRacing haces cola en Dirección de Carrera.",
        "iRacing no tiene música épica, solo tus gritos cuando pierdes el coche.",
        "iRacing: porque los errores cuestan iRating, autoestima y ganas de vivir.",
        "iRacing es como tener un jefe exigente, pero con ruedas.",
        "¿Te gusta chocar y seguir? Entonces sigue jugando arcade.",
        "En iRacing te sacan bandera negra hasta por existir mal.",
        "La única cosa más estricta que iRacing es tu suegra.",
        "Otros simulan conducción. iRacing simula presión arterial alta.",
        "ACC se juega. iRacing se sobrevive.",
        "En iRacing puedes estar solo en pista y aún sentir ansiedad.",
        "iRacing: cuando «corro por diversión» ya no existe.",
        "El respeto en pista de iRacing no lo ves ni en reuniones familiares.",
        "Otros juegos te dejan ser agresivo. En iRacing te dejan en boxes.",
        "El único sitio más hostil que iRacing es Twitter.",
        "iRacing no te recompensa por participar. Te destroza si fallas.",
        "En iRacing, el warm-up da más miedo que la carrera.",
        "iRacing es tan real que puedes perder amigos por adelantar mal.",
        "En otros simus tocas y sigues. En iRacing dices Sorry y sonries.",
        "No juegas iRacing, te conviertes en víctima de iRacing.",
        "iRacing es el único sitio donde te insultan con telemetría.",
        "Si iRacing fuera una persona, estaría en terapia.",
        "Jugar a iRacing con ratón es como ir a la guerra con una cuchara.",
        "Otros tienen replays bonitos. iRacing tiene traumas grabados.",
        "¿Frenaste mal? iRacing te lo recuerda toda la semana.",
        "Otros te dicen «bien jugado». iRacing te manda a la escuela otra vez.",
        "iRacing: donde cada milímetro cuenta... para morirte más lento.",
        "Forza tiene logros. iRacing tiene cicatrices.",
        "ACC tiene clima dinámico. iRacing tiene caos programado.",
        "En otros puedes cambiar la dificultad. En iRacing, tú eres el problema.",
        "iRacing te enseña humildad... a base de accidentes.",
        "La curva de aprendizaje de iRacing está detrás de una curva ciega.",
        "En iRacing los errores se pagan con tu alma digital.",
        "¿Quieres un simulador? Empieza por llorar en iRacing.",
        "iRacing: donde los fantasmas no son rivales, son tus errores pasados.",
        "No necesitas enemigos si corres en iRacing.",
        "iRacing: el único juego donde practicar te hace dudar de ti mismo.",
        "F1 23 tiene flashbacks. iRacing tiene trauma en directo.",
        "iRacing convierte una curva mal tomada en una crisis existencial.",
        "Otros juegos simulan coches. iRacing simula arrepentimientos.",
        "iRacing: donde una vuelta buena vale más que todo tu pasado gamer.",
        "Cuando pruebas iRacing, lo demás te parece de Fisher-Price.",
        "iRacing no tiene historia. Tú la escribes... y la sufres.",
        "ACC es para aprender. iRacing es para pagar por sufrir.",
        "iRacing no es un juego. Es una sentencia voluntaria.",
        "La comunidad de iRacing no te odia. Te ignora con superioridad.",
        "En iRacing no se gana. Se sobrevive más que el resto.",
        "Project Cars 2: para cuando iRacing es demasiado real para ti.",
        "iRacing: donde no hay ayudas ni para llorar.",
        "Tu primera vuelta en iRacing es la última vez que sonreíste.",
        "Frenar tarde en iRacing se paga con vacaciones en la grava.",
        "Si quieres respeto en pista, empieza por llorar en iRacing.",
        "iRacing es el simulador más serio que tendrás sin firmar un contrato.",
        "En iRacing, la práctica no hace al maestro. Te mantiene vivo.",
        "El verdadero boss final de los simuladores se llama iRating.",
        "La mayor mentira: «esta curva la paso a fondo» en iRacing.",
        "iRacing: el único juego que te da pesadillas con Spa.",
        "El matchmaking de iRacing te hace rezar antes de cada salida.",
        "No hay botón de reiniciar en iRacing, solo el de rendirse.",
        "iRacing no tiene trucos. Solo tiene reglas y dolor.",
        "¿Quedaste P17 en iRacing? ¡Felicidades, no chocaste!",
        "iRacing es el único simulador donde verás más protestas que en Twitter.",
        "En iRacing, cada coche tiene personalidad... y todas odian al piloto.",
        "iRacing no necesita gráficos ultra. Suena a trauma y se siente igual.",
        "En ACC puedes pilotar. En iRacing te examinan en cada curva.",
        "¿Miedo escénico? Prueba una quali en iRacing y hablamos.",
        "iRacing: donde las carreras duran 20 minutos y las quejas toda la semana.",
        "En otros simus corres por diversión. En iRacing por tu dignidad.",
        "El único combustible en iRacing es tu ansiedad.",
        "No hay tuning en iRacing, solo llanto y presión de ruedas.",
        "Cada vez que dices «solo una más» en iRacing, pierdes SR.",
        "En iRacing hasta los warm-up son combates psicológicos.",
        "ACC es relajante después de un día duro. iRacing lo hace peor.",
        "¿Chocaste? Bienvenido al club de los frustrados de iRacing.",
        "En iRacing puedes perder puntos sin tocar a nadie.",
        "No compites en iRacing, te enfrentas a la realidad.",
        "Forza tiene skins. iRacing tiene cicatrices digitales.",
        "iRacing no es pay-to-win. Es pay-to-sufrir.",
        "¿Tu mejor tiempo? iRacing lo ignora y te castiga igual.",
        "En iRacing puedes aprender a ser mejor o dejar de jugar.",
        "La primera regla de iRacing: no hables de iRacing... solo llora.",
        "iRacing: el simulador que no sabías que necesitabas para hundirte emocionalmente.",
        "Tu licencia en iRacing vale más que tu autoestima.",
        "iRacing es donde los errores viven para siempre... en los replays.",
        "ACC tiene clima dinámico. iRacing tiene caos meteorológico con traumas incluidos.",
        "iRacing: la única suscripción que te cobra por destruirte emocionalmente.",
        "¿Te diviertes en iRacing? Estás jugando mal.",
        "iRacing no tiene mods, tiene miseria controlada.",
        "No necesitas amigos si corres en iRacing. Los pierdes rápido.",
        "En iRacing cada salida es una promesa rota.",
        "ACC tiene lluvia bonita. En iRacing llueve y lloras.",
        "La curva más peligrosa en iRacing es la curva de expectativas.",
        "iRacing: donde la vuelta perfecta solo existe hasta que te ve alguien.",
        "¿Quieres aprender humildad? Empieza un campeonato en iRacing.",
        "ACC es un juego. iRacing es un castigo voluntario.",
        "Tu mayor rival en iRacing eres tú... y tu conexión.",
        "iRacing no te enseña a correr, te enseña a sufrir con estilo.",
        "Solo hay dos tipos de pilotos en iRacing: los que han llorado, y los que mienten.",
        "Cada carrera en iRacing es un recordatorio de que no eres tan bueno como pensabas."
        "En Iracing, la carrera da mas miedo que la protesta",
        "En Iracing, la curva 1 es el muro de la realidad",
        "En Iracing, la curva 2 es el muro de la desesperación",
        "En Iracing, la curva 3 es el muro de la frustración",
        "En Iracing, la curva 4 es el muro de la resignación",
        "En Iracing, la curva 5 es el muro de la aceptación",
        "En Iracing, la curva 6 es el muro de la locura",
        "En Iracing, la curva 7 es el muro de la desesperanza",
        "En Iracing, la curva 8 es el muro de la tristeza",
        "En Iracing, la curva 9 es el muro de la ira",
        "En Iracing, la curva 10 es el muro de la desesperación",
        "Donde el x4 es el pan de cada dia",
        "Pase lo que pase no hables de monos",
]