valorant_phrases = [
    "🎯 Si no das tiros, da excusas, funciona igual.",
    "💣 Spike plantada, pero las neuronas desactivadas.",
    "😅 Cuando el team entero rushea sin plan, es arte abstracto.",
    "🔫 Headshot perdido… culpa de la física.",
    "💥 Ultimates usados… y nadie muere.",
    "👀 Camper invisible, o solo confundido.",
    "🕹️ Team descoordinado… nivel profesional en caos.",
    "💣 Spike desactivada… por un enemigo invisible.",
    "🎯 Disparo perfecto… y el enemigo ya se fue.",
    "😅 Triple kill imaginario… solo en tus sueños.",
    "🔫 Ráfaga de balas… al aire, estilo artístico.",
    "💥 Granadas lanzadas… al lado contrario del enemigo.",
    "👀 Scout perdido… nadie sabe dónde está.",
    "🕹️ Estrategia del team: caos absoluto.",
    "💣 Spike plantada… y tu compañero estaba en otra zona.",
    "🎯 Disparo crítico… y el ping lo arruina todo.",
    "😅 Clutch imposible… pero intentémoslo igual.",
    "🔫 Headshot fallido… culpa del lag, claro.",
    "💥 Ultimate usado… y nadie muere.",
    "👀 Vigilancia constante… y aun así te flanquean.",
    "🕹️ Team sin comunicación… nivel experto en desastre.",
    "💣 Spike desactivada… por un troll profesional.",
    "🎯 Disparo perfecto… enemigo teleportado.",
    "😅 El que siempre muere primero… protagonista del desastre.",
    "🔫 Ráfaga de balas… al objetivo equivocado.",
    "💥 Habilidad usada… sin efecto alguno.",
    "👀 Camper que se mueve… rompe todo el suspense.",
    "🕹️ Estrategia del team: confusión total.",
    "💣 Spike plantada… y tu compañero olvidó desactivarla.",
    "🎯 Disparo al corazón… enemigo ya muerto.",
    "😅 Clutch imposible… y aún así fallas.",
    "🔫 Headshot imaginario… solo tú lo viste.",
    "💥 Explosión perfecta… en la pared.",
    "👀 Scout invisible… y tú también.",
    "🕹️ Team rushea… sin plan, caos garantizado.",
    "💣 Spike desactivada… por tu propio equipo.",
    "🎯 Tiro crítico… que nunca alcanzó al enemigo.",
    "😅 Triple kill frustrante… solo en tu imaginación.",
    "🔫 Ráfaga al aire… estilo Star Wars.",
    "💥 Ultimate desperdiciado… arte abstracto en acción.",
    "👀 Camper escondido… nivel maestro de paciencia.",
    "🕹️ Estrategia: improvisación total.",
    "💣 Spike plantada… pero el enemigo está detrás de ti.",
    "🎯 Disparo perfecto… enemigo inmortal, claro.",
    "😅 Clutch perdido… culpa del lag.",
    "🔫 Headshot perdido… por 0,01ms.",
    "💥 Granadas usadas… estilo desastre creativo.",
    "👀 Scout perdido… nivel experto en desaparición.",
    "🕹️ Team sin coordinación… caos garantizado.",
    "💣 Spike desactivada… y tú solo mirabas.",
    "🎯 Tiro crítico… que falla por la física del juego.",
    "😅 Triple kill imaginario… nivel frustración máxima.",
    "🔫 Ráfaga de balas… al objetivo equivocado otra vez.",
    "💥 Ultimate usado… sin efecto, casualidad diaria.",
    "👀 Camper visible… pero nadie le dispara.",
    "🕹️ Estrategia improvisada… desastre asegurado.",
    "💣 Spike plantada… y tu compañero en otra zona.",
    "🎯 Disparo perfecto… enemigo teleportado otra vez.",
    "😅 Clutch imposible… y aún así lo intentas.",
    "🔫 Headshot imaginario… solo tú lo crees.",
    "💥 Explosión perfecta… en la pared de fondo.",
    "👀 Scout invisible… nadie lo encuentra.",
    "🕹️ Team rushea… caos total y diversión garantizada.",
    "💣 Spike desactivada… por tu propio amigo.",
    "🎯 Disparo crítico… enemigo inmortal, típico.",
    "😅 Triple kill frustrante… solo en tus sueños.",
    "🔫 Ráfaga al aire… estilo desastre total.",
    "💥 Ultimate desperdiciado… arte del fracaso.",
    "👀 Camper escondido… nivel maestro del aburrimiento.",
    "🕹️ Estrategia: improvisación creativa.",
    "💣 Spike plantada… enemigo justo detrás de ti.",
    "🎯 Disparo perfecto… enemigo inmortal, obvio.",
    "😅 Clutch perdido… culpa del ping, claro.",
    "🔫 Headshot perdido… por milímetros de azar.",
    "💥 Granadas usadas… y el objetivo intacto.",
    "👀 Scout perdido… nivel experto en invisibilidad.",
    "🕹️ Team sin coordinación… desastre absoluto.",
    "💣 Spike desactivada… mientras mirabas.",
    "🎯 Tiro crítico… que falla por culpa de la física.",
    "😅 Triple kill imaginario… frustración total.",
    "🔫 Ráfaga de balas… al enemigo equivocado.",
    "💥 Ultimate usado… y nadie muere, clásico.",
    "👀 Camper visible… pero todos ignoran.",
    "🕹️ Estrategia improvisada… caos asegurado.",
    "💣 Spike plantada… y tu compañero olvidó desactivarla.",
    "🎯 Disparo perfecto… enemigo teleportado, típico.",
    "😅 Clutch imposible… pero lo intentas igual.",
    "🔫 Headshot imaginario… solo tú lo crees otra vez.",
    "💥 Explosión perfecta… en la pared del fondo.",
    "👀 Scout invisible… nadie lo detecta.",
    "🕹️ Team rushea… caos total y diversión garantizada.",
    "💣 Spike desactivada… por tu amigo distraído.",
    "🎯 Disparo crítico… enemigo inmortal, nivel frustración.",
    "😅 Triple kill frustrante… solo en tu imaginación.",
    "🔫 Ráfaga al aire… desastre creativo total.",
    "💥 Ultimate desperdiciado… arte del fracaso confirmado.",
    "👀 Camper escondido… aburrimiento garantizado.",
    "🕹️ Estrategia: improvisación máxima.",
    "💣 Spike plantada… enemigo justo detrás de ti."
]
