ban_phrases = [
    "🔨 @{objetivo} ha sido baneado… de la nevera. Sin cervezas por una semana.",
    "🚫 @{objetivo} baneado por exceso de velocidad en la silla gamer.",
    "📜 @{objetivo} baneado según la sección 404 del reglamento inexistente.",
    "🔒 @{objetivo} baneado temporalmente hasta que aprenda a girar a la izquierda.",
    "🛑 @{objetivo} baneado por intentar hackear el puesto del comentarista.",
    "🪦 @{objetivo} baneado… pero solo de la lista de cumpleaños.",
    "🤖 @{objetivo} baneado por la IA por conducta sospechosamente humana.",
    "❌ @{objetivo} baneado porque el bot se levantó con el pie izquierdo.",
    "⚠️ @{objetivo} baneado hasta que encuentre la trazada correcta.",
    "🧹 @{objetivo} baneado y enviado a barrer la pista.",
    "🥶 @{objetivo} baneado y congelado en carbonita.",
    "🏁 @{objetivo} baneado por salir antes que el semáforo.",
    "💥 @{objetivo} baneado por chocar contra la línea de meta.",
    "🎭 @{objetivo} baneado por interpretar mal el papel de piloto.",
    "📦 @{objetivo} baneado y enviado por paquetería urgente.",
    "🕳️ @{objetivo} baneado y lanzado a un agujero negro.",
    "💣 @{objetivo} baneado por explosión espontánea de mal gusto.",
    "🦘 @{objetivo} baneado por saltarse todas las curvas.",
    "🥴 @{objetivo} baneado por conducir en zigzag intencionalmente.",
    "🧟 @{objetivo} baneado por parecer un NPC defectuoso.",
    "🚓 @{objetivo} baneado por la policía de las trazadas.",
    "🍌 @{objetivo} baneado por tirar plátanos en la pista.",
    "🔥 @{objetivo} baneado por prender fuego al pitlane.",
    "🛟 @{objetivo} baneado y enviado a dar vueltas en la piscina.",
    "🪤 @{objetivo} baneado por caer en su propia trampa.",
    "🗿 @{objetivo} baneado por quedarse parado como estatua.",
    "📉 @{objetivo} baneado por bajada extrema de rendimiento.",
    "🪁 @{objetivo} baneado por volar sin licencia.",
    "🎯 @{objetivo} baneado por usar a otros pilotos como diana.",
    "🥊 @{objetivo} baneado por boxeo en plena recta.",
    "⛷️ @{objetivo} baneado por esquiar en el asfalto.",
    "🪙 @{objetivo} baneado por intentar pagar con monedas de chocolate.",
    "🚷 @{objetivo} baneado por conducir en sentido contrario.",
    "🎢 @{objetivo} baneado por convertir la pista en una montaña rusa.",
    "🥗 @{objetivo} baneado por usar la pista como huerto urbano.",
    "🪚 @{objetivo} baneado por serrar el volante a mitad de carrera.",
    "📢 @{objetivo} baneado por narrar su propia derrota en altavoz.",
    "🪞 @{objetivo} baneado por maquillarse en plena curva.",
    "🏹 @{objetivo} baneado por disparar flechas a los rivales.",
    "🎰 @{objetivo} baneado por apostar contra sí mismo.",
    "💾 @{objetivo} baneado por intentar guardar la partida en la vida real.",
    "📺 @{objetivo} baneado por cambiar de canal en plena carrera.",
    "🍕 @{objetivo} baneado por detenerse a comer pizza.",
    "🧨 @{objetivo} baneado por usar dinamita en la pista.",
    "🪿 @{objetivo} baneado por soltar gansos en la recta final.",
    "🛸 @{objetivo} baneado por ser abducido en plena vuelta.",
    "🚀 @{objetivo} baneado por despegar en lugar de correr.",
    "🪫 @{objetivo} baneado por quedarse sin batería a mitad de carrera.",
    "🎃 @{objetivo} baneado por asustar a los rivales vestido de calabaza.",
    "🧊 @{objetivo} baneado por congelar el circuito entero."
]