slogans_phrases = [
        "Acelera hasta que las dudas desaparezcan.",
        "Si no derrapas, no estás intentando lo suficiente.",
        "El freno es solo una sugerencia.",
        "Corre como si la meta te debiera dinero.",
        "Más gas, menos drama.",
        "Las curvas son oportunidades para presumir.",
        "El límite de velocidad es solo una recomendación.",
        "Menos miedo, más motor.",
        "La recta es para coches rápidos, las curvas para pilotos valientes.",
        "Acelerar cura el alma.",
        "Si todo parece bajo control, no vas lo bastante rápido.",
        "El asfalto es mi oficina.",
        "Corre limpio… o al menos que parezca.",
        "Cada curva es una historia.",
        "Velocidad y precisión, la combinación ganadora.",
        "No mires atrás, no vas en esa dirección.",
        "El podio es mi zona de confort.",
        "Si frenas, que sea para saludar.",
        "Corre como si no hubiera mañana.",
        "El ruido del motor es mi idioma.",
        "Gasolina y café: combustible de campeones.",
        "Las reglas están para interpretarlas… rápido.",
        "No corro para ganar, corro para no perder.",
        "El miedo frena más que cualquier pedal.",
        "La meta no espera a nadie.",
        "Cada segundo cuenta… y yo los cobro caros.",
        "No hay curva imposible, solo trazadas mal hechas.",
        "Si quieres respeto, gana carreras.",
        "El cronómetro no miente.",
        "En la pista, el silencio es derrota.",
        "Los héroes se hacen a alta velocidad.",
        "Si no está en rojo, no está al límite.",
        "La pista es mi templo.",
        "Menos excusas, más vueltas rápidas.",
        "No importa el coche, importa el piloto.",
        "Los frenos están sobrevalorados.",
        "Cada vuelta es un nuevo récord… o un buen intento.",
        "El público quiere espectáculo, yo se lo doy.",
        "En la pista no hay amigos, solo rivales.",
        "El motor no se enfría, se apaga.",
        "Si no quema, no vale la pena.",
        "La meta es solo el principio.",
        "El turbo es mi religión.",
        "Mi combustible: adrenalina.",
        "En carrera, la suerte se fabrica.",
        "Si dudas, acelera.",
        "La bandera a cuadros es mi llamada.",
        "Cada salida es una batalla.",
        "Velocidad sin control no sirve… pero es divertida.",
        "Si no vibras, revisa tu pulso.",
        "Los límites son para los demás."
]