witty_phrases = [
    'Veo que tus dedos funcionan, ¿pero el cerebro también participa o es espectador?',
    '¿Vienes a ver el stream o a practicar tus habilidades para molestar?',
    'Tu aportación al chat es tan valiosa como una piedra en el zapato.',
    'Gracias por tu mensaje, ahora mi inteligencia ha bajado 2 puntos.',
    '¿Siempre comentas sin pensar o hoy es un día especial?',
    'Si tu objetivo es destacar, enhorabuena, lo lograste por lo absurdo.',
    'Tus ideas son como el WiFi de McDonald’s: lentas y abiertas a todos.',
    'No sé si eres troll o simplemente así de natural. Ambas dan miedo.',
    '¡Wow! Otro comentario inútil que nadie pidió, pero aquí estamos.',
    'Eres como ese NPC que siempre dice lo mismo. Pero con menos carisma.',
    '¿Este mensaje fue tu intento de humor? Devuélvelo a fábrica.',
    'Con ese comentario ganaste el premio al espectador más invisible.',
    'Tu opinión es como un DLC malo: nadie la pidió y molesta.',
    'Sigue así y pronto serás mod... pero de un canal abandonado.',
    'Tu presencia se siente... como un lagazo inesperado.',
    'Gracias por escribir, ahora sabemos lo que no hay que decir.',
    '¿Ese mensaje era en serio o estás en modo random hoy?',
    'Un aplauso para el esfuerzo. ¿El resultado? Ya lo juzga el chat.',
    'Si fueras un coche de carreras, estarías en marcha atrás.',
    'Tus chistes hacen llorar a los payasos.',
    'No te digo que eres malo, pero el chat de voz se silencia solo cuando hablas.',
    'Con ese comentario demuestras que pensar está sobrevalorado.',
    'Tienes la agudeza de un plátano maduro.',
    'Podrías ser útil... si fuéramos a estudiar el comportamiento molesto.',
    '¿Has probado apagar y encender tu sentido común?',
    'Cada vez que comentas, se pierde una neurona... y no era mía.',
    'Eres como una advertencia en la carretera: molestas pero necesarias.',
    'Tus mensajes deberían venir con subtítulos... y disculpas.',
    'Unlike tu comentario: 0/10, no lo volvería a leer.',
    'Gracias por tu contribución al caos.',
    'Sigue así y desbloqueas el logro: “Fastidio legendario”.',
    '¿Estás bien? Porque ese comentario no lo está.',
    'La lógica y tú sois como el aceite y el agua.',
    'Me recuerdas a los bugs: aparecen sin avisar y arruinan el momento.',
    '¿Te entrenas para esto o simplemente se te da mal naturalmente?',
    '¡Qué comentario más… interesante! En otro universo.',
    'No cambies nunca… aunque eso sería ideal.',
    'Si tus aportes fueran gasolina, nos quedábamos tirados.',
    'Tus frases tienen menos sentido que mis setups en iRacing.',
    'Eres la razón por la que hay moderadores.',
    '¿Puedes repetir eso? Es que el cringe fue tan fuerte que no escuché.',
    'Agradecemos tu comentario, ahora vuelve a tu cueva.',
    'Lo tuyo es arte... pero arte abstracto y sin sentido.',
    'Cuando crees que has visto todo, aparece tu mensaje.',
    'Gracias por recordarnos por qué existe el botón de ban.',
    '¡Campeón del comentario irrelevante! Tu trofeo está en camino.',
    'Hablas más que los frenos de mi coche cuando no los cambio.',
    'Tu mensaje fue tan útil como un semáforo en el desierto.',
    '¿Tienes un filtro? Porque tu cerebro claramente no.',
    '¿Sabías que puedes pensar antes de escribir? Revolucionario, lo sé.',
    'El chat estaba bien... hasta que escribiste.',
    '¿Alguien pidió un comentario innecesario? No, pero llegó igual.',
    'Tienes talento, pero no sé para qué.',
    'Tu mensaje fue tan random que hasta el bot lo ignoró.',
    'Si hubiera un campeonato de tonterías, ya tendrías podio.',
    'Eres como el lag: molesto y siempre presente.',
    'Cada letra que escribes me hace replantear seguir en Twitch.',
    'Hablas mucho para alguien que nunca dice nada.',
    'Tus palabras no duelen, pero dan pena.',
    '¡Nivel de aporte al chat: -3!',
    'Eres tan original como una skin repetida.',
    'Aportas tanto como un spoiler sin contexto.',
    'Tienes menos ritmo que un modem de los 90.',
    'Tus comentarios se imprimen en braille del cringe.',
    '¿Eso fue ironía, sarcasmo o simplemente falta de lógica?',
    'Eres tan útil como un GPS sin satélites.',
    '¿Estás en una misión para desconcentrar? Vas bien.',
    'Con esa actitud ni los bots te siguen.',
    'Gracias, ahora necesito terapia.',
    'Sigue comentando, que para eso tengo antibióticos.',
    'Tu opinión importa… pero en otro canal.',
    'Eres tan molesto como el tutorial que no se puede saltar.',
    'Si existiera el premio al viewer más random, tendrías el trofeo vitalicio.',
    'Tus letras pesan más que mis errores en pista.',
    'Eres como un DLC caro: nadie te quiere pero apareces igual.',
    '¿Alguna vez pensaste antes de escribir? Prueba, es divertido.',
    'Estás a un paso de que el bot te dé vacaciones.',
    'Tu presencia es como el eco: vuelve cuando nadie lo espera.',
    'No eres el peor… pero estás nominado.',
    'Tu teclado pide ayuda cada vez que te ve llegar.',
    'El nivel de sentido de tu comentario está en negativo.',
    'Tienes el carisma de un semáforo en rojo.',
    'No sé si eso fue una broma, pero fue trágico.',
    'Eres el ejemplo perfecto de lo que no hay que escribir.',
    'Tu comentario fue como el tráfico en hora punta: insoportable.',
    '¡Atención! Comentario sin sentido a la vista.',
    'Te esfuerzas… pero no se nota.',
    'Si hablar fuera talento, estarías en bronce.',
    'Podrías ser streamer, pero de estática.',
    'Me haces pensar que el mute fue inventado por algo.',
    'Tus mensajes me dan más miedo que el setup de serie.',
    'Sigue así y el bot aprenderá a ignorarte solo.',
    'Eres el tipo de espectador que hace que los lurkers tengan razón.',
    'Eres tan claro como el reglamento de Twitch.',
    'Con ese comentario me bajó el IQ.',
    'Tus frases podrían usarse para tortura psicológica.',
    'Gracias, ahora el chat parece un foro del 2006.',
    'Eres como una alerta en OBS: evitable pero molesta.',
    'Si fueras contenido, serías “contenido irrelevante”.',
    'Tienes más salidas en falso que yo en iRacing.',
    'Tu sentido del humor es un glitch permanente.',
    'Cada mensaje tuyo es un plot twist sin gracia.',
    'Sigue hablando… así me acuerdo por qué activo el slowmode.',
]

# --- Frases amigables para usuarios "amigables" ---
friendly_compliments_phrases = [
    ", siempre es un placer verte por aquí! 😄",
    "¡Hey! Gracias por estar presente, tu energía se nota. 🌟",
    ", tu buen rollo ilumina el chat! 💖",
    "¡Qué alegría tenerte en el directo! 😎",
    "Siempre un gusto ver a participando en la conversación. 👍",
    ", tu presencia hace que todo sea más divertido! 😂",
    "¡Gracias por tu apoyo! Eres de los mejores aquí. 💙",
    ", tus comentarios siempre levantan el ánimo del chat! ✨",
    "¡Qué buena vibra traes! Sigue así 😎",
    ", sin ti este chat sería mucho más aburrido! 🎉",
    ", me encanta cómo aportas siempre! 😁",
    "¡Hey, gracias por animar a todos! 🌈",
    ", eres la chispa del chat hoy! ⚡",
    ", tu entusiasmo es contagioso! 💥",
    "¡Gracias, por hacer que cada directo sea mejor! 💛",
    ", tu energía positiva no pasa desapercibida! 😎",
    ", siempre es divertido leer tus mensajes! 😂",
    ", me alegra que estés aquí compartiendo! 💖",
    "¡Hey, qué gusto verte conectado! 🌟",
    ", tu presencia siempre suma al chat! 🎊"
]

# --- Frases sarcásticas para usuarios "antipáticos" ---
unfriendly_cheating_phrases = [
    ", ¿otra vez tú? No podía faltar. 😏",
    "Wow, tu entrada ilumina el chat... de aburrimiento. 🙄",
    ", si tus comentarios fueran gasolina, este chat estaría en llamas 🔥... de tedio.",
    "Ah, justo lo que necesitábamos: otra opinión inútil. 😑",
    "Gracias, tu negatividad siempre ayuda... a dormir. 💤",
    ", cada vez que hablas, un unicornio pierde su brillo. 🦄",
    ", Qué alegría verte, casi igual que encontrar una piedra en el camino. 🪨",
    ", tus consejos son como spoilers de mala película. 🎬",
    "¡Mira quién llegó! el héroe de la mediocridad. 🏆",
    ", tus palabras siempre me hacen reflexionar... en qué desastre acabará el chat. 🤔",
    "Ahí estás como siempre, repartiendo confusión gratis. 😅",
    ", tus mensajes son como memes malos: nadie los quiere pero siguen apareciendo! 😂",
    "Gracias por tu aporte, realmente no lo necesitábamos. 🙃",
    " hablando claro: tu participación es opcional y debería seguir siéndolo. 😏",
    " Qué sorpresa verte, como una nube gris en un día soleado. ☁️",
    ", tu talento para molestar es casi artístico. 🎨",
    "Ah, el rey/reina de los comentarios que nadie pidió. 👑",
    ", tu intervención ilumina todo... pero solo para que veamos lo aburrido que es esto! 💡",
    ", me encanta cuando hablas… ¡pero sólo para practicar mi paciencia! 😬",
    "Otra vez tú? ¡Qué emocionante… si tuviera sarcasmo suficiente! 😒"
]
