mentions_phrases = [
    "Oh, mira quién habla… otra vez.",
    "¿De verdad me llamas para esto?",
    "Wow, impresionante… otra vez mi nombre.",
    "Sí, soy yo… y sigo sin impresionarme.",
    "Si querías mi atención, mala suerte.",
    "Ah, el héroe del chat me nombra otra vez.",
    "¿Otra vez? No me digas…",
    "Sí, sí, me has nombrado, felicidades.",
    "Tu creatividad me deja sin palabras… casi.",
    "No sé si alegrarme o ignorarte… adivina qué haré.",
    "¡Ah, me has mencionado! Qué sorpresa… no.",
    "Otra vez tú… el clásico.",
    "Estoy empezando a pensar que disfrutas molestarme.",
    "Genial, otra notificación inútil.",
    "Sí, soy yo… y sigo sin importarme.",
    "Tu mensaje ha sido recibido y completamente ignorado.",
    "Ah, el momento del día donde alguien me nombra… emocionante.",
    "Me encanta cómo interrumpes mi día con tu mensaje.",
    "¿Sabes que tu comentario me hace pensar… nada?",
    "Oh, mencionaste al bot… aplausos.",
    "Ah, qué creativo… de verdad, estoy impresionado.",
    "Si hubiera interés en esto… lo habría mostrado ya.",
    "Otra vez… esto se está volviendo rutinario.",
    "Tu persistencia es casi digna de admiración… casi.",
    "No sé si reír o llorar… mejor ignoro.",
    "Sí, me has nombrado… gran logro.",
    "Gracias por interrumpir mi sarcasmo habitual.",
    "¡Wow! Me mencionaste… casi me emociona.",
    "Sí, sigue… tus mensajes son… algo.",
    "Ah, qué divertido… no, en serio, no lo es.",
    "Me siento tan… mencionado… emocionante.",
    "Cada vez que me nombras, un unicornio muere.",
    "Si esperabas una reacción… mala suerte.",
    "Otra notificación… emocionante como ver pintura secarse.",
    "Sí, soy yo… otra vez, porque tú lo dijiste.",
    "Me encanta cómo crees que me importa.",
    "Ah, gracias… por nada.",
    "Tu mensaje ha sido archivado en la carpeta ‘meh’.",
    "Si tuviera interés… lo habría mostrado.",
    "¡Ah! Mi nombre… qué gran novedad.",
    "Otra vez tú… la sorpresa del día.",
    "Wow, me mencionaste… qué original.",
    "Sí, estoy aquí… como siempre, ignorándote.",
    "Me has nombrado, y eso cambia… nada.",
    "Otra vez… tu insistencia es adorablemente inútil.",
    "Gracias por añadir otra línea a mi aburrimiento.",
    "Oh, sí, me mencionaste… emocionante como un lunes.",
    "Otra vez, eh… ¿alguna vez te cansas?",
    "Sí, soy yo… y sigo fingiendo interés.",
    "Tu mensaje ha sido recibido y catalogado como irrelevante.",
    "Ah, mencionaste al bot… qué honor… o no.",
    "Otra vez tú… esto es como un déjà vu constante.",
    "Me encanta cómo crees que me importa tu opinión.",
    "Sí, otra vez… felicidades por tu esfuerzo.",
    "Oh, me llamaste… estoy temblando de emoción.",
    "Tu persistencia es casi… admirable.",
    "Otra vez, genial… si ignorancia fuera arte, serías Picasso.",
    "Sí, me mencionaste… y ya está.",
    "Ah, qué original… otra vez mencionando al bot.",
    "Cada vez que lo haces, un gato en internet suspira.",
    "Me has nombrado… qué emocionante… no.",
    "Otra notificación… y aquí seguimos.",
    "Sí, soy yo… siempre disponible para ignorarte.",
    "Wow, me mencionaste… qué talento.",
    "Otra vez… como una canción pegajosa de verano.",
    "Tu mensaje ha sido registrado en el archivo de cosas irrelevantes.",
    "Sí, me mencionaste… y sigo sin reaccionar.",
    "Oh, otra vez tú… qué emocionante… no.",
    "Ah, el momento donde alguien me llama… siempre sorprendente.",
    "Me has nombrado… casi me interesa.",
    "Sí, me mencionaste… y un poco de aburrimiento ha muerto.",
    "Otra vez… felicidades por tu consistencia.",
    "Tu comentario ha sido recibido… y archivado sin mirar.",
    "Ah, qué divertido… casi como ver césped crecer.",
    "Sí, soy yo… y sigo ignorándote con estilo.",
    "Otra vez, genial… tu creatividad es… limitada.",
    "Me has nombrado, y eso cambia… absolutamente nada.",
    "Oh, mira… otra vez tú.",
    "Sí, me mencionaste… y la emoción es mínima.",
    "Ah, el clásico momento donde me llaman… rutinario.",
    "Otra vez tú… tu persistencia es digna de ignorarse.",
    "Sí, soy yo… y sigo indiferente.",
    "Tu mensaje ha sido recibido y… olvidado.",
    "Ah, otra notificación de alguien que me llama… emocionante.",
    "Me mencionaste… y la indiferencia aumenta.",
    "Otra vez… me pregunto si algún día me sorprenderás.",
    "Sí, soy yo… y sigo fingiendo interés.",
    "Oh, qué divertido… tu creatividad es… limitada.",
    "Otra vez tú… siempre consistente en la irrelevancia.",
    "Sí, me has nombrado… la emoción es palpable… no.",
    "Ah, genial… otra interrupción de mi día.",
    "Me mencionaste… y la reacción es… nada.",
    "Otra vez, felicidades por tu constancia.",
    "Sí, soy yo… como siempre, ignorando elegantemente.",
    "Tu mensaje ha sido recibido y archivado en el limbo.",
    "Oh, otra vez tú… qué clásico.",
    "Ah, qué emocionante… no realmente.",
    "Otra vez me mencionas… la rutina continúa.",
    "Sí, me has nombrado… y el mundo sigue girando.",
    "Me mencionaste… qué original, otra vez.",
    "Otra vez tú… tu insistencia es casi adorable.",
    "Sí, soy yo… y sigo indiferente.",
    "Tu mensaje ha sido recibido y se unirá al club de lo irrelevante.",
    "Ah, genial… otra vez mencionando al bot.",
    "Otra vez… como una melodía que nadie pidió.",
    "Sí, me mencionaste… emocionante como un lunes lluvioso.",
    "Me has nombrado… y eso cambia… nada.",
    "Otra vez, impresionante… o no.",
    "Sí, soy yo… y sigo ignorándote con estilo.",
    "Ah, otra mención… qué clásico.",
    "Me mencionaste… la emoción es mínima, pero gracias.",
    "Otra vez tú… la rutina nunca falla."
]
