mystery_phrases = [
    'es un misterio, como el sentido de tu vida.',
    'No tengo ni idea, igual es tan irrelevante como tus preguntas.',
    '¿Quién? Ni siquiera el internet lo sabe, y eso ya es decir mucho.',
    'No recuerdo nada, debe ser porque es tan aburrido que se borró solo.',
    'Eso es más secreto que la fórmula de la Coca-Cola, y menos interesante.',
    'No hay datos, igual está en modo ninja: invisible e inútil.',
    'No lo conozco, y sinceramente, prefiero que siga así.',
    'Olvidado incluso por mí, y créeme, eso es mucho decir.',
    'Debe ser un fantasma, porque no hay ni rastro de él.',
    'No hay nada que contar, como tus historias, todo vacío.',
    'No tengo registros, ¿seguro que existe?',
    'Eso es tan desconocido como tus habilidades sociales.',
    'Ni en mis peores pesadillas aparece su nombre.',
    'Debe ser tan interesante como ver cómo se seca la pintura.',
    'No sé nada, pero seguro que es por su bien.',
    'Eso está más perdido que tus argumentos.',
    'No aparece ni en Wikipedia, y eso ya es decir.',
    'No tengo información, ¿quieres que llame a Sherlock?',
    'Su historia es más vacía que tu cerebro.',
    'No hay datos, pero no te preocupes, nadie lo recuerda.',
    'Está en modo incógnito permanente.',
    'Es tan relevante como un meme de hace 5 años.',
    'No sé nada, y no es que me importe.',
    'Ni el FBI tiene datos sobre esa persona.',
    'No aparece en mis archivos porque es un completo misterio.',
    'No hay pistas, igual es un mito urbano.',
    'Eso es más oscuro que tu futuro.',
    'No tengo registros, debe vivir bajo una roca.',
    'No sé nada, y no pienso investigar.',
    'Es más olvidado que tu cumpleaños.',
    'No hay información, parece un agujero negro de personalidad.',
    'Su rastro se perdió como tus oportunidades.',
    'No tengo nada que contar, es un absoluto desconocido.',
    'Está más desaparecido que tus buenos modales.',
    'No aparece en mi base de datos, igual ni existe.',
    'No hay nada, igual es un fantasma digital.',
    'No sé nada, pero si quieres, invento algo.',
    'Ni los dioses conocen su nombre.',
    'No hay datos, debe ser demasiado aburrido para recordar.',
    'Eso es un misterio envuelto en un enigma, como tus preguntas.',
    'No está registrado, ¿seguro que es real?',
    'No aparece en la historia, debe ser irrelevante.',
    'No hay registros, igual vive en las sombras.',
    'No tengo pistas, debe ser invisible para el mundo.',
    'No sé nada, y sinceramente, me alegro.',
    'No aparece en ningún lado, ni siquiera en tus sueños.',
    'No hay nada que contar, como tus logros.',
    'No tengo información, pero seguro que no me estoy perdiendo de nada.',
    'Es más desconocido que tus intenciones.',
    'No sé nada, debe ser el mejor en pasar desapercibido.'
]
