
sarcastic_phrases = [
        "Yo no me estrellé, el muro se cruzó.",
        "Esa curva me tenía manía.",
        "Es estrategia, no lentitud.",
        "El coche va solo, yo solo miro.",
        "¡Eso fue lag, no error mío!",
        "¿Frenar? Eso es para cobardes.",
        "Mi setup es arte abstracto.",
        "Si derrapas, es que vas rápido.",
        "Las banderas azules son solo sugerencias.",
        "Yo conduzco con estilo... poco efectivo, pero estilo.",
        "Chocar es una forma de expresión.",
        "No perdí el control, solo estaba explorando el circuito.",
        "Si no hay humo, no hay emoción.",
        "Lo importante es participar... en los choques.",
        "Error de sistema, seguro.",
        "¿Safety rating? ¿Eso se come?",
        "He inventado una nueva trazada.",
        "Mi coche tiene vida propia.",
        "La curva me sorprendió por la espalda.",
        "Mi estrategia es impredecible, incluso para mí.",
        "¿Líneas ideales? Yo creo las mías.",
        "Voy más rápido cuando no me miran.",
        "No es accidente, es simulación inmersiva.",
        "Los pianos me odian.",
        "Choqué, pero con estilo.",
        "Hoy conduzco en modo YOLO.",
        "No fue error, fue experimento.",
        "Mis neumáticos están en huelga.",
        "El freno está sobrevalorado.",
        "No sabía que eso era una curva.",
        "Mi coche decidió ser artista.",
        "Estaba practicando acrobacias.",
        "¡Eso fue simulación realista de caos!",
        "Estoy guardando neumáticos... desde la vuelta 1.",
        "No me adelantó, me dejó atrás por compasión.",
        "Mi coche es edición limitada: sin control.",
        "No choqué, solo di cariño a la barrera.",
        "Yo conduzco por inspiración, no por lógica.",
        "Ese trompo fue para entretener a los espectadores.",
        "Lo hago por el show, no por el podio.",
        "Las marchas son orientativas.",
        "Las paredes aparecen de la nada.",
        "¿Mi línea de carrera? Libre interpretación.",
        "Hoy estoy testeando los límites del juego.",
        "Eso fue simulación avanzada de errores.",
        "Mi volante tiene vida propia.",
        "Eso no fue off-track, fue exploración.",
        "Estoy probando nueva física cuántica.",
        "Los demás no entienden mi ritmo artístico.",
        "Mis errores son parte del plan... que no tengo.",
        "Ese trompo era para calentar neumáticos.",
        "No me salí, me expandí.",
        "Voy probando todas las trazadas posibles, por ciencia.",
        "Mi vuelta rápida es metafórica.",
        "La simulación es tan real que da miedo.",
        "No estoy lento, estoy disfrutando del paisaje.",
        "Estoy inventando el 'drift racing'.",
        "Me adelantan por respeto, no por velocidad.",
        "A veces me gusta ver el coche desde otros ángulos.",
        "No fue accidente, fue una maniobra evasiva artística.",
        "Yo no fallo, la simulación sí.",
        "La curva cambió desde la última vuelta, lo juro.",
        "Conduzco mejor cuando no pienso.",
        "No me quedé sin gasolina, estoy más ligero.",
        "Esto no es perder, es diferenciarse.",
        "Cada golpe es una historia.",
        "Estoy aquí por el ruido del motor, no por competir.",
        "No es falta de práctica, es exceso de creatividad.",
        "Mi coche solo obedece si lo aplauden.",
        "Frené… mentalmente.",
        "Yo no practico, improviso.",
        "¿Cuántas curvas tiene esta pista? ¡Demasiadas!",
        "Mi coche y yo estamos en desacuerdo.",
        "Puse setup de lluvia… en seco. Detalles.",
        "No freno tarde, freno con emoción.",
        "Estoy corriendo en modo documental: lento pero profundo.",
        "Es culpa del force feedback emocional.",
        "¿Setup? Uso el predeterminado por rebeldía.",
        "No me salí, tomé un atajo emocional.",
        "Me adelantaron porque querían más protagonismo.",
        "Mi coche patina porque está feliz.",
        "No me choqué, simplemente cambié de decorado.",
        "Yo corro con el alma, no con el pedal.",
        "No iba por fuera, iba por libre.",
        "El radar miente, te lo juro.",
        "¿Qué curva? No la vi.",
        "No me adelantaron, cambiamos de dimensión.",
        "Mi línea es creativa, no tradicional.",
        "Voy tan lento que el tiempo se detiene.",
        "Esa penalización fue artística.",
        "Cada error es un paso hacia el descontrol total.",
        "¿Respeto al rival? Claro, por eso le di un beso lateral.",
        "Yo no hago tiempos, creo momentos.",
        "iRacing sin sarcasmo no es iRacing.",
        "No choqué, solo comprobé la resistencia del frontal.",
        "No es que me estrelle, es que tengo otra filosofía de frenada.",
        "Estoy escribiendo poesía con mis trazadas.",
        "Mi coche se reseteó a la Edad Media.",
        "Lo que hago no son errores, son performances.",
        "El pit lane me atrae, es magnético.",
        "No voy lento, voy en modo nostalgia.",
        "¡Mira mamá, sin manos!... y sin puntos también.",
        "Yo no giro mal, es el universo que gira raro.",
        "En iRacing todos somos pilotos... hasta que giramos.",
        "Soy más constante que el lag.",
        "No es trompo, es rotación emocional.",
        "Mi coche está calibrado con intuición.",
        "No me fui largo, fue un viaje espiritual.",
        "Los pianos son trampas ninja.",
        "Esa curva tiene trampa legal.",
        "Mi setup lo hice con los ojos cerrados.",
        "Eso no fue lento, fue elegante.",
        "Mi línea de carrera está patrocinada por el caos.",
        "Los muros deberían esquivarme, no al revés.",
        "Cada golpe es una lección que ignoro.",
        "Ese impacto fue intencional… según mi subconsciente.",
        "Yo corro con el corazón, no con los frenos.",
        "El juego me tiene envidia.",
        "No practico porque soy puro talento… sin dirección.",
        "No fallé, simplemente fui fiel a mi estilo.",
        "Me salí para ver si seguía cargando el circuito.",
        "Mis errores están bien distribuidos.",
        "Tengo talento... para hacer lo inesperado.",
        "¿Practicar antes de correr? ¿Y perder la emoción?",
        "Estoy haciendo un documental sobre cómo no correr.",
        "Esa curva me troleó.",
        "No choqué, hice arte cinético.",
        "La vuelta rápida es para conformistas.",
        "No fui último, fui el más reflexivo.",
        "Mi coche solo va bien en gravedad cero.",
        "La pista está en mi contra, y lo sabe.",
        "No me salgo, me expando estratégicamente.",
        "Los otros pilotos no entienden mi genialidad.",
        "No me penalizaron, me valoraron artísticamente.",
        "Conduzco como hablo: sin filtros.",
        "Mis frenadas cuentan como sustos controlados.",
        "Voy lento para que me admiren más tiempo.",
        "Es que nadie me avisó que las curvas giran.",
        "No uso telemetría, uso la fuerza.",
        "El coche pidió vacaciones en la curva 3.",
        "Todo está bajo control… de otro.",
        "Voy más recto que mis decisiones.",
        "No giré mal, giré diferente.",
        "El muro y yo teníamos asuntos pendientes.",
        "Hoy estoy practicando el automasaje frontal.",
        "Me salí de pista porque la realidad apesta.",
        "En mi mente todo iba perfecto.",
        "La pista no respeta mi arte.",
        "Ese trompo fue un homenaje al caos.",
        "Mi coche y yo tenemos una relación abierta.",
        "Hoy conduzco como si no hubiera SR.",
        "He redefinido la palabra desastre.",
        "Esa curva tenía mala vibra.",
        "El coche necesita terapia, no gasolina.",
        "No es lag, es dramatismo digital.",
        "Voy más perdido que el freno en curva.",
        "No pierdo, me reinvento cada vuelta.",
        "No soy lento, estoy calibrando el universo.",
        "Todo esto es parte de un metajuego mental.",
        "Si no me entiendes, no eres digno de mi ritmo.",
        "No practico errores, los perfecciono.",
        "No compito, inspiro.",
        "Voy tan lento que el safety car me adelanta.",
        "iRacing me teme, por eso me sabotea.",
        "No son fallos, son momentos virales."
]