X1_PHRASES = [
    "🌾 Excursión por el césped: el piloto decidió salirse un poquito de la pista para comprobar si estaba recién cortado, x1",
    "👀 Eso fue una visita turística por la hierba; parece que el asfalto hoy no era suficiente para su talento, x1",
    "🧭 El GPS dijo por ahí para ahorrar unos metros y el piloto obedeció sin hacerse muchas preguntas, x1",
    "⚠️ Límites de pista opcionales: ¿quién necesita asfalto cuando tienes todo un campo para explorar a placer?, x1",
    "🌱 Probando el agarre del césped con mucho estilo; un pequeño test de agricultura en plena competición, x1",
    "🚗💨 Todo bajo control... al menos mientras estemos fuera de la pista y no haya muros cerca, x1",
    "🤏 Se le fue un poquito la mano en la salida; nada grave pero los sensores ya han tomado nota, x1",
    "🟡 Aviso leve: salida de pista sin mayores consecuencias, solo un pequeño susto para el cronómetro, x1",
    "🌾 Agricultura intensiva en la zona de curvas; el piloto está recolectando muestras de tierra con el chasis, x1",
    "👋 Hola grava, un saludo amistoso del piloto que ha decidido bajar a saludarte personalmente, x1",
    "🧠 El piloto pensó que entraba sobrado en la curva, pero la física le recordó que la pista tiene límites, x1",
    "😌 Tranquilos, solo es un pequeño x1 de nada; estamos explorando rutas alternativas para el futuro",
    "🚦 Cortando camino como si nadie estuviera mirando por las cámaras de seguridad del circuito, x1",
    "📏 Ese piano estaba un poco lejos, pero decidimos tocarlo de todos modos para no dejarlo solo, x1",
    "🌿 Paseo por la naturaleza mientras competimos; un poco de aire fresco para los neumáticos no viene mal, x1",
    "👀 Dirección de carrera mira fijamente pero no dice nada todavía; el piloto está jugando con fuego, x1",
    "🧪 Probando límites extremos... el resultado ha sido un reprobado claro en cuanto a trazada oficial, x1",
    "🤷 Cosas que pasan cuando se corre con tanto estilo que la pista se te queda demasiado pequeña, x1",
    "🛣️ Pista alternativa descubierta; explorando el césped por si hay algún atajo secreto que nadie conoce, x1",
    "🌾 La hierba también cuenta vueltas en esta carrera y hoy ya lleva unos cuantos metros recorridos, x1",
    "🚗💭 El coche se abrió solo y decidió irse de paseo; el piloto jura que él no ha tenido nada que ver, x1",
    "📉 Pequeño error de cálculo del piloto; nada crítico pero suficiente para ensuciar un poco las gomas, x1",
    "🟡 Aviso amistoso de salida de pista; la próxima vez intenta mantener al menos dos ruedas en lo negro, x1",
    "🌱 Reforestación completada gracias a una conducción creativa y un poco fuera de los márgenes legales, x1",
    "😎 Nada grave de lo que preocuparse, solo un x1 de puro estilo para darle emoción a la retransmisión, x1",
    "👣 Salida momentánea de la pista; el césped aplaude al paso del coche mientras el piloto sufre, x1",
    "🧭 Ruta panorámica activada por decisión unilateral del piloto; disfrutando de las vistas exteriores, x1",
    "🚧 Fuera de pista pero sin drama ninguno; todos tranquilos que aquí no se ha roto nada todavía, x1",
    "🤏 Unos milímetros de más que marcan la diferencia entre una vuelta perfecta y una visita al campo, x1",
    "🌿 El césped saluda con alegría cada paso de las ruedas; hoy estamos haciendo muchos amigos fuera, x1",
    "🛞 Ruedas fuera de sitio pero el orgullo sigue intacto; seguimos empujando como si nada hubiera pasado, x1",
    "📸 Foto fuera de pista: un bonito recuerdo de ese paseo inesperado por las escapatorias del circuito, x1",
    "👀 Controlado... más o menos; digamos que la salida estaba planeada para asustar un poco a los rivales, x1",
    "🧠 Decisión creativa que desafía las normas establecidas por la dirección de carrera en el briefing, x1",
    "🌾 Turismo rural en medio de la carrera; el piloto ha decidido tomarse un respiro del asfalto caliente, x1",
    "🚦 Atajo ilegal detectado y registrado en los servidores; los comisarios están arqueando una ceja, x1",
    "😅 Ups, un pequeño error sin importancia que solo nos ha costado unas décimas y un poco de suciedad, x1",
    "📐 Entró pasado de revoluciones y lo admitimos sin problemas; la frenada se quedó un poco corta, x1",
    "🌱 El coche necesitaba un poco de aire fresco y ha optado por una salida momentánea por la hierba, x1",
    "🟡 Nada que declarar a los comisarios, solo ha sido un alarde de estilo sobre la superficie verde, x1",
    "🚗💨 Demasiada alegría al volante y muy poca precisión en el vértice de la curva; resultado: x1",
    "🧭 Se perdió un segundo explorando la pista alternativa; la aventura es parte del ADN de este piloto, x1",
    "🌿 Jardinería racing: cortando el césped con las ruedas traseras para dejar el circuito impecable, x1",
    "🤷 Error sin consecuencias graves para el coche, solo pura diversión fuera de las líneas blancas, x1",
    "🛞 Pisando fuera con mucho orgullo; a veces lo mejor de la pista está justo donde termina el piano, x1",
    "📏 Esa curva engaña hasta al mejor de los pilotos; el piano ha escupido al coche con delicadeza, x1",
    "😌 Todo sigue su curso normal, simplemente hemos decidido ensanchar un poco el trazado original, x1",
    "🌾 Modo excursión activado: disfrutando del paisaje mientras los demás se pelean por el asfalto, x1",
    "🟡 Aviso suavecito del sistema: recordatorio amistoso de que la carrera se corre por lo negro, x1",
]