X2_PHRASES = [
    "😬 El coche decidió que hoy no le apetecía obedecer y se fue por donde quiso, x2",
    "🧠 El piloto juraba por radio que lo tenía bajo control, pero la física dijo otra cosa, x2",
    "🎢 Un poco de drifting no intencionado para darle emoción y pánico a la curva, x2",
    "🤡 Un trompo espectacular patrocinado por un setup que nadie terminó de entender, x2",
    "🚗💨 Le sobró demasiada fe en el pedal derecho y le faltó bastante grip en las gomas, x2",
    "⚠️ Esto ha sido un aviso serio de que el muro está mucho más cerca de lo que parece, x2",
    "😅 Digamos que eso ya no fue precisamente una trazada limpia de escuela de pilotos, x2",
    "🛞 Las ruedas delanteras dijeron basta y se declararon en huelga de agarre absoluto, x2",
    "🧠 Alerta de confianza excesiva detectada: el piloto cree que lleva un imán en el chasis, x2",
    "🎠 Una vueltita artística de 360 grados para saludar al público y ver el paisaje, x2",
    "🤷 Se fue completamente solo, o al menos eso es lo que el piloto le contará al equipo, x2",
    "📉 Error importante de los que duelen y restan muchos segundos valiosos en el crono, x2",
    "🚧 Pérdida de control confirmada; la telemetría está echando chispas ahora mismo, x2",
    "😬 Eso se salvó de puro milagro, aunque la dignidad del piloto se quedó en el piano, x2",
    "🛞 El eje trasero decidió que tenía prisa y quiso adelantar al morro por fuera, x2",
    "🧠 El piloto quería ir a la derecha pero el setup tenía planes muy diferentes, x2",
    "🎢 Un giro inesperado de los acontecimientos que nos ha dejado a todos con la boca abierta, x2",
    "🤡 Un show totalmente gratis para el público; espectáculo puro a costa del tiempo, x2",
    "🚗💭 Tenía demasiada prisa por llegar a la meta y se olvidó de pasar por la curva, x2",
    "⚠️ Dirección de carrera ya ha sacado la libreta y empieza a apuntar la matrícula, x2",
    "😅 Esto ya empieza a doler de verdad, tanto al orgullo como al estado del coche, x2",
    "📐 Una entrada demasiado optimista que terminó en una excursión forzada por el césped, x2",
    "🛞 Parece que hoy el grip se vendía por separado y el piloto no compró el pack, x2",
    "🧠 Un error de cálculo matemático que ha terminado con el coche mirando a Cuenca, x2",
    "🎠 Lo llamaremos trompo técnico para que no parezca que ha sido un error de manos, x2",
    "🤷 El coche se cruzó por completo y el piloto se convirtió en un simple pasajero, x2",
    "🚧 Un aviso más que claro de que los límites de la pista no son una sugerencia, x2",
    "😬 Se podría decir que se ha salvado a medias, porque el susto no se lo quita nadie, x2",
    "📉 Una pérdida de tiempo seria que va a obligar a remontar con el cuchillo entre los dientes, x2",
    "🛞 Un derrape innecesario que ha dejado las ruedas traseras pidiendo la jubilación, x2",
    "🧠 El piloto tiene las manos mucho más rápidas de lo que su propio coche puede digerir, x2",
    "🎢 Una patinada de categoría premium digna de una exhibición de Holiday on Ice, x2",
    "🤡 Aquí tenemos una clase magistral de cómo perder el norte en menos de un segundo, x2",
    "🚗💨 Ha dado gas mucho antes de tiempo y el motor ha decidido adelantar al chasis, x2",
    "⚠️ Este es ya el segundo aviso; el tercero vendrá acompañado de una bonita sanción, x2",
    "😅 Claramente eso no estaba en el plan estratégico que prepararon antes de salir, x2",
    "📐 Demasiado volante y muy poca paciencia; la receta perfecta para el desastre, x2",
    "🛞 Adiós definitivo al agarre; a partir de aquí todo ha sido cuestión de inercia y suerte, x2",
    "🧠 El piloto soñó con una trazada imposible y la realidad le ha despertado de golpe, x2",
    "🎠 Rotación completa ejecutada con éxito, aunque no era exactamente lo que buscábamos, x2",
    "🤷 Son cosas del directo, aunque a veces el directo sea un poco cruel con el piloto, x2",
    "🚧 El control se ha perdido por completo y ahora solo queda esperar a que el coche pare, x2",
    "😬 El coche ha protestado de forma violenta ante semejante maniobra del piloto, x2",
    "📉 Un error claro de bulto que va a traer cola en la reunión técnica de después, x2",
    "🧠 Una falta de tacto evidente en el momento más crítico de la frenada, x2",
    "🎢 Nos ha regalado un show lateral digno de las mejores películas de acción, x2",
    "🤡 Un trompo de edición deluxe para recordar que la pista hoy está muy delicada, x2",
    "🚗💨 Demasiado optimismo concentrado en un solo pedal; el resultado era previsible, x2",
]